import RelationalFoundations.Diagnostics
set_option linter.defProp false
set_option linter.checkUnivs false
namespace AbstractSegmentedTurning.CoreCoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoreCoupledTurningConclusion («admittedPositiveBoundaryRejected»)
end AbstractSegmentedTurning.CoreCoupledTurningConclusion
namespace AbstractSegmentedTurning.UniformRegimeExit
export RelationalFoundations.Diagnostics.UniformRegimeExit («reindex_id»)
end AbstractSegmentedTurning.UniformRegimeExit
namespace AbstractSegmentedTurning.RegimeExit.mk
export RelationalFoundations.Diagnostics.RegimeExit.mk («sizeOf_spec»)
end AbstractSegmentedTurning.RegimeExit.mk
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («CoupledObstructedRegime»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.PositiveResidualBoundary.mk
export RelationalFoundations.Diagnostics.PositiveResidualBoundary.mk («sizeOf_spec»)
end AbstractSegmentedTurning.PositiveResidualBoundary.mk
namespace AbstractSegmentedTurning.BoundaryGenerator
export RelationalFoundations.Diagnostics.BoundaryGenerator («mk»)
end AbstractSegmentedTurning.BoundaryGenerator
namespace AbstractSegmentedTurning.PositiveResidualBoundary
export RelationalFoundations.Diagnostics.PositiveResidualBoundary («strict»)
end AbstractSegmentedTurning.PositiveResidualBoundary
namespace AbstractSegmentedTurning.CoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoupledObstructedRegime («ctorIdx»)
end AbstractSegmentedTurning.CoupledObstructedRegime
namespace AbstractSegmentedTurning.RegimeExit
export RelationalFoundations.Diagnostics.RegimeExit («restrictRegime_comp»)
end AbstractSegmentedTurning.RegimeExit
namespace AbstractSegmentedTurning.CoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoupledTurningConclusion («ctorIdx»)
end AbstractSegmentedTurning.CoupledTurningConclusion
namespace AbstractSegmentedTurning.ObstructedRegime
export RelationalFoundations.Diagnostics.ObstructedRegime («Regime»)
end AbstractSegmentedTurning.ObstructedRegime
namespace AbstractSegmentedTurning.TurningConclusion
export RelationalFoundations.Diagnostics.TurningConclusion («continuationOutsideRegime»)
end AbstractSegmentedTurning.TurningConclusion
namespace AbstractSegmentedTurning.ObstructedRegime
export RelationalFoundations.Diagnostics.ObstructedRegime («continuation_outside_regime»)
end AbstractSegmentedTurning.ObstructedRegime
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («CoupledTurningConclusion»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.SegmentedBoundary
export RelationalFoundations.Diagnostics.SegmentedBoundary («extension»)
end AbstractSegmentedTurning.SegmentedBoundary
namespace AbstractSegmentedTurning.RegimeExit
export RelationalFoundations.Diagnostics.RegimeExit («mk»)
end AbstractSegmentedTurning.RegimeExit
namespace AbstractSegmentedTurning.CoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoupledObstructedRegime («interpretResidual»)
end AbstractSegmentedTurning.CoupledObstructedRegime
namespace AbstractSegmentedTurning.ObstructedRegime
export RelationalFoundations.Diagnostics.ObstructedRegime («canonicalRegime»)
end AbstractSegmentedTurning.ObstructedRegime
namespace AbstractSegmentedTurning.CorePositiveResidualBoundary
export RelationalFoundations.Diagnostics.CorePositiveResidualBoundary («positive»)
end AbstractSegmentedTurning.CorePositiveResidualBoundary
namespace AbstractSegmentedTurning.BoundaryGenerator
export RelationalFoundations.Diagnostics.BoundaryGenerator («ctorIdx»)
end AbstractSegmentedTurning.BoundaryGenerator
namespace AbstractSegmentedTurning.CoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoupledObstructedRegime («continuation_outside_regime»)
end AbstractSegmentedTurning.CoupledObstructedRegime
namespace AbstractSegmentedTurning.CoreCoupledTurningConclusion.mk
export RelationalFoundations.Diagnostics.CoreCoupledTurningConclusion.mk («sizeOf_spec»)
end AbstractSegmentedTurning.CoreCoupledTurningConclusion.mk
namespace AbstractSegmentedTurning.ObstructedRegime
export RelationalFoundations.Diagnostics.ObstructedRegime («classifyOrTotalize»)
end AbstractSegmentedTurning.ObstructedRegime
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («CoreTurningConclusion»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.CoreCoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoreCoupledObstructedRegime («Attempt»)
end AbstractSegmentedTurning.CoreCoupledObstructedRegime
namespace AbstractSegmentedTurning.CoreCoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoreCoupledObstructedRegime («canonicalRegime»)
end AbstractSegmentedTurning.CoreCoupledObstructedRegime
namespace AbstractSegmentedTurning.RegimeExit
export RelationalFoundations.Diagnostics.RegimeExit («mapFaithful_comp»)
end AbstractSegmentedTurning.RegimeExit
namespace AbstractSegmentedTurning.BoundaryGenerator.mk
export RelationalFoundations.Diagnostics.BoundaryGenerator.mk («sizeOf_spec»)
end AbstractSegmentedTurning.BoundaryGenerator.mk
namespace AbstractSegmentedTurning.RegimeExit
export RelationalFoundations.Diagnostics.RegimeExit («ctorIdx»)
end AbstractSegmentedTurning.RegimeExit
namespace AbstractSegmentedTurning.CoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoupledObstructedRegime («mk»)
end AbstractSegmentedTurning.CoupledObstructedRegime
namespace AbstractSegmentedTurning.CoreTurningConclusion
export RelationalFoundations.Diagnostics.CoreTurningConclusion («ctorIdx»)
end AbstractSegmentedTurning.CoreTurningConclusion
namespace AbstractSegmentedTurning.UniformRegimeExit
export RelationalFoundations.Diagnostics.UniformRegimeExit («reindexImplementation»)
end AbstractSegmentedTurning.UniformRegimeExit
namespace AbstractSegmentedTurning.CoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoupledObstructedRegime («analyzeRegime»)
end AbstractSegmentedTurning.CoupledObstructedRegime
namespace AbstractSegmentedTurning.PositiveResidualBoundary
export RelationalFoundations.Diagnostics.PositiveResidualBoundary («ctorIdx»)
end AbstractSegmentedTurning.PositiveResidualBoundary
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («PositiveResidualBoundary»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.CoreCoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoreCoupledObstructedRegime («exactClassification»)
end AbstractSegmentedTurning.CoreCoupledObstructedRegime
namespace AbstractSegmentedTurning.CorePositiveResidualBoundary
export RelationalFoundations.Diagnostics.CorePositiveResidualBoundary («core»)
end AbstractSegmentedTurning.CorePositiveResidualBoundary
namespace AbstractSegmentedTurning.CoreTurningConclusion
export RelationalFoundations.Diagnostics.CoreTurningConclusion («uniqueResidualOccurrence»)
end AbstractSegmentedTurning.CoreTurningConclusion
namespace AbstractSegmentedTurning.CoreCoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoreCoupledTurningConclusion («ctorIdx»)
end AbstractSegmentedTurning.CoreCoupledTurningConclusion
namespace AbstractSegmentedTurning.SegmentedBoundary
export RelationalFoundations.Diagnostics.SegmentedBoundary («positive»)
end AbstractSegmentedTurning.SegmentedBoundary
namespace AbstractSegmentedTurning.BoundaryGenerator
export RelationalFoundations.Diagnostics.BoundaryGenerator («generates»)
end AbstractSegmentedTurning.BoundaryGenerator
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («coupledTurning»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.RegimeExit
export RelationalFoundations.Diagnostics.RegimeExit («mapFaithful_id»)
end AbstractSegmentedTurning.RegimeExit
namespace AbstractSegmentedTurning.CoreTurningConclusion
export RelationalFoundations.Diagnostics.CoreTurningConclusion («mk»)
end AbstractSegmentedTurning.CoreTurningConclusion
namespace AbstractSegmentedTurning.CoreCoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoreCoupledObstructedRegime («no_strict_regime_extension»)
end AbstractSegmentedTurning.CoreCoupledObstructedRegime
namespace AbstractSegmentedTurning.CoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoupledObstructedRegime («Attempt»)
end AbstractSegmentedTurning.CoupledObstructedRegime
namespace AbstractSegmentedTurning.CoreCoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoreCoupledTurningConclusion («continuationOutsideRegime»)
end AbstractSegmentedTurning.CoreCoupledTurningConclusion
namespace AbstractSegmentedTurning.CoupledObstructedRegime.mk
export RelationalFoundations.Diagnostics.CoupledObstructedRegime.mk («sizeOf_spec»)
end AbstractSegmentedTurning.CoupledObstructedRegime.mk
namespace AbstractSegmentedTurning.TurningConclusion
export RelationalFoundations.Diagnostics.TurningConclusion («totalizationRejected»)
end AbstractSegmentedTurning.TurningConclusion
namespace AbstractSegmentedTurning.CoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoupledObstructedRegime («Interpretation»)
end AbstractSegmentedTurning.CoupledObstructedRegime
namespace AbstractSegmentedTurning.CoreTurningConclusion
export RelationalFoundations.Diagnostics.CoreTurningConclusion («generatedContinuation»)
end AbstractSegmentedTurning.CoreTurningConclusion
namespace AbstractSegmentedTurning.UniformRegimeExit
export RelationalFoundations.Diagnostics.UniformRegimeExit («reindex_comp»)
end AbstractSegmentedTurning.UniformRegimeExit
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («SegmentedBoundary»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («UniformRegimeExit»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.CoreTurningConclusion
export RelationalFoundations.Diagnostics.CoreTurningConclusion («exactRelativeClassification»)
end AbstractSegmentedTurning.CoreTurningConclusion
namespace AbstractSegmentedTurning.CoreCoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoreCoupledObstructedRegime («mk»)
end AbstractSegmentedTurning.CoreCoupledObstructedRegime
namespace AbstractSegmentedTurning.ObstructedRegime
export RelationalFoundations.Diagnostics.ObstructedRegime («Interpretation»)
end AbstractSegmentedTurning.ObstructedRegime
namespace AbstractSegmentedTurning.UniformRegimeExit
export RelationalFoundations.Diagnostics.UniformRegimeExit («atImplementation»)
end AbstractSegmentedTurning.UniformRegimeExit
namespace AbstractSegmentedTurning.RegimeExit
export RelationalFoundations.Diagnostics.RegimeExit («mapFaithful_restrictRegime»)
end AbstractSegmentedTurning.RegimeExit
namespace AbstractSegmentedTurning.CoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoupledTurningConclusion («generatedContinuation»)
end AbstractSegmentedTurning.CoupledTurningConclusion
namespace AbstractSegmentedTurning.ExactRegimeClassification
export RelationalFoundations.Diagnostics.ExactRegimeClassification («regimeImpliesEquality»)
end AbstractSegmentedTurning.ExactRegimeClassification
namespace AbstractSegmentedTurning.CorePositiveResidualBoundary
export RelationalFoundations.Diagnostics.CorePositiveResidualBoundary («context»)
end AbstractSegmentedTurning.CorePositiveResidualBoundary
namespace AbstractSegmentedTurning.CoreTurningConclusion
export RelationalFoundations.Diagnostics.CoreTurningConclusion («noStrictRegimeExtension»)
end AbstractSegmentedTurning.CoreTurningConclusion
namespace AbstractSegmentedTurning.CoreCoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoreCoupledObstructedRegime («Interpretation»)
end AbstractSegmentedTurning.CoreCoupledObstructedRegime
namespace AbstractSegmentedTurning.ObstructedRegime
export RelationalFoundations.Diagnostics.ObstructedRegime («mk»)
end AbstractSegmentedTurning.ObstructedRegime
namespace AbstractSegmentedTurning.PositiveResidualBoundary
export RelationalFoundations.Diagnostics.PositiveResidualBoundary («context»)
end AbstractSegmentedTurning.PositiveResidualBoundary
namespace AbstractSegmentedTurning.CoupledTurningConclusion.mk
export RelationalFoundations.Diagnostics.CoupledTurningConclusion.mk («sizeOf_spec»)
end AbstractSegmentedTurning.CoupledTurningConclusion.mk
namespace AbstractSegmentedTurning.PositiveResidualBoundary
export RelationalFoundations.Diagnostics.PositiveResidualBoundary («positive»)
end AbstractSegmentedTurning.PositiveResidualBoundary
namespace AbstractSegmentedTurning.SegmentedBoundary
export RelationalFoundations.Diagnostics.SegmentedBoundary («mk»)
end AbstractSegmentedTurning.SegmentedBoundary
namespace AbstractSegmentedTurning.CoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoupledObstructedRegime («no_strict_regime_extension»)
end AbstractSegmentedTurning.CoupledObstructedRegime
namespace AbstractSegmentedTurning.TurningConclusion
export RelationalFoundations.Diagnostics.TurningConclusion («exactRelativeClassification»)
end AbstractSegmentedTurning.TurningConclusion
namespace AbstractSegmentedTurning.TurningConclusion.mk
export RelationalFoundations.Diagnostics.TurningConclusion.mk («sizeOf_spec»)
end AbstractSegmentedTurning.TurningConclusion.mk
namespace AbstractSegmentedTurning.CoreCoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoreCoupledTurningConclusion («exactRelativeClassification»)
end AbstractSegmentedTurning.CoreCoupledTurningConclusion
namespace AbstractSegmentedTurning.ExactRegimeClassification.mk
export RelationalFoundations.Diagnostics.ExactRegimeClassification.mk («sizeOf_spec»)
end AbstractSegmentedTurning.ExactRegimeClassification.mk
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («CoreCoupledTurningConclusion»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.ObstructedRegime
export RelationalFoundations.Diagnostics.ObstructedRegime («ctorIdx»)
end AbstractSegmentedTurning.ObstructedRegime
namespace AbstractSegmentedTurning.ObstructedRegime.mk
export RelationalFoundations.Diagnostics.ObstructedRegime.mk («sizeOf_spec»)
end AbstractSegmentedTurning.ObstructedRegime.mk
namespace AbstractSegmentedTurning.CorePositiveResidualBoundary.mk
export RelationalFoundations.Diagnostics.CorePositiveResidualBoundary.mk («sizeOf_spec»)
end AbstractSegmentedTurning.CorePositiveResidualBoundary.mk
namespace AbstractSegmentedTurning.CoreCoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoreCoupledObstructedRegime («ctorIdx»)
end AbstractSegmentedTurning.CoreCoupledObstructedRegime
namespace AbstractSegmentedTurning.TurningConclusion
export RelationalFoundations.Diagnostics.TurningConclusion («generatedContinuation»)
end AbstractSegmentedTurning.TurningConclusion
namespace AbstractSegmentedTurning.CoreCoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoreCoupledTurningConclusion («generatedContinuation»)
end AbstractSegmentedTurning.CoreCoupledTurningConclusion
namespace AbstractSegmentedTurning.CoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoupledObstructedRegime («toCoreCoupled»)
end AbstractSegmentedTurning.CoupledObstructedRegime
namespace AbstractSegmentedTurning.BoundaryGenerator
export RelationalFoundations.Diagnostics.BoundaryGenerator («extensionIrreflexive»)
end AbstractSegmentedTurning.BoundaryGenerator
namespace AbstractSegmentedTurning.CoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoupledObstructedRegime («toObstructedRegime»)
end AbstractSegmentedTurning.CoupledObstructedRegime
namespace AbstractSegmentedTurning.CoreCoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoreCoupledObstructedRegime («toObstructedRegime»)
end AbstractSegmentedTurning.CoreCoupledObstructedRegime
namespace AbstractSegmentedTurning.CoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoupledObstructedRegime («Regime»)
end AbstractSegmentedTurning.CoupledObstructedRegime
namespace AbstractSegmentedTurning.ExactRegimeClassification
export RelationalFoundations.Diagnostics.ExactRegimeClassification («ctorIdx»)
end AbstractSegmentedTurning.ExactRegimeClassification
namespace AbstractSegmentedTurning.TurningConclusion
export RelationalFoundations.Diagnostics.TurningConclusion («ctorIdx»)
end AbstractSegmentedTurning.TurningConclusion
namespace AbstractSegmentedTurning.RegimeExit
export RelationalFoundations.Diagnostics.RegimeExit («mapFaithful»)
end AbstractSegmentedTurning.RegimeExit
namespace AbstractSegmentedTurning.CoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoupledTurningConclusion («exactRelativeClassification»)
end AbstractSegmentedTurning.CoupledTurningConclusion
namespace AbstractSegmentedTurning.ExactRegimeClassification
export RelationalFoundations.Diagnostics.ExactRegimeClassification («equalityBuildsRegime»)
end AbstractSegmentedTurning.ExactRegimeClassification
namespace AbstractSegmentedTurning.BoundaryGenerator
export RelationalFoundations.Diagnostics.BoundaryGenerator («boundary»)
end AbstractSegmentedTurning.BoundaryGenerator
namespace AbstractSegmentedTurning.CoreTurningConclusion.mk
export RelationalFoundations.Diagnostics.CoreTurningConclusion.mk («sizeOf_spec»)
end AbstractSegmentedTurning.CoreTurningConclusion.mk
namespace AbstractSegmentedTurning.TurningConclusion
export RelationalFoundations.Diagnostics.TurningConclusion («noStrictRegimeExtension»)
end AbstractSegmentedTurning.TurningConclusion
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («coreTurning»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.BoundaryGenerator
export RelationalFoundations.Diagnostics.BoundaryGenerator («continuation»)
end AbstractSegmentedTurning.BoundaryGenerator
namespace AbstractSegmentedTurning.CoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoupledTurningConclusion («mk»)
end AbstractSegmentedTurning.CoupledTurningConclusion
namespace AbstractSegmentedTurning.TurningConclusion
export RelationalFoundations.Diagnostics.TurningConclusion («uniqueResidualOccurrence»)
end AbstractSegmentedTurning.TurningConclusion
namespace AbstractSegmentedTurning.CoreSegmentedBoundary
export RelationalFoundations.Diagnostics.CoreSegmentedBoundary («ctorIdx»)
end AbstractSegmentedTurning.CoreSegmentedBoundary
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («BoundaryGenerator»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.CoreCoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoreCoupledObstructedRegime («rejectTotalization»)
end AbstractSegmentedTurning.CoreCoupledObstructedRegime
namespace AbstractSegmentedTurning.CoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoupledTurningConclusion («noStrictRegimeExtension»)
end AbstractSegmentedTurning.CoupledTurningConclusion
namespace AbstractSegmentedTurning.CoreCoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoreCoupledObstructedRegime («admittedPositiveBoundary_rejected»)
end AbstractSegmentedTurning.CoreCoupledObstructedRegime
namespace AbstractSegmentedTurning.RegimeExit
export RelationalFoundations.Diagnostics.RegimeExit («restrictRegime»)
end AbstractSegmentedTurning.RegimeExit
namespace AbstractSegmentedTurning.CoreSegmentedBoundary.mk
export RelationalFoundations.Diagnostics.CoreSegmentedBoundary.mk («sizeOf_spec»)
end AbstractSegmentedTurning.CoreSegmentedBoundary.mk
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («CoreCoupledObstructedRegime»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.UniformRegimeExit
export RelationalFoundations.Diagnostics.UniformRegimeExit («reindex_at»)
end AbstractSegmentedTurning.UniformRegimeExit
namespace AbstractSegmentedTurning.CoreCoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoreCoupledObstructedRegime («analyzeRegime»)
end AbstractSegmentedTurning.CoreCoupledObstructedRegime
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («CoreSegmentedBoundary»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.CoreCoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoreCoupledObstructedRegime («interpretResidual»)
end AbstractSegmentedTurning.CoreCoupledObstructedRegime
namespace AbstractSegmentedTurning.CoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoupledObstructedRegime («exactClassification»)
end AbstractSegmentedTurning.CoupledObstructedRegime
namespace AbstractSegmentedTurning.RegimeExit
export RelationalFoundations.Diagnostics.RegimeExit («candidate»)
end AbstractSegmentedTurning.RegimeExit
namespace AbstractSegmentedTurning.CoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoupledTurningConclusion («continuationOutsideRegime»)
end AbstractSegmentedTurning.CoupledTurningConclusion
namespace AbstractSegmentedTurning.CoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoupledTurningConclusion («admittedPositiveBoundaryRejected»)
end AbstractSegmentedTurning.CoupledTurningConclusion
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («CorePositiveResidualBoundary»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («abstractTurning»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.RegimeExit
export RelationalFoundations.Diagnostics.RegimeExit («restrictRegime_id»)
end AbstractSegmentedTurning.RegimeExit
namespace AbstractSegmentedTurning.CoreCoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoreCoupledTurningConclusion («mk»)
end AbstractSegmentedTurning.CoreCoupledTurningConclusion
namespace AbstractSegmentedTurning.ObstructedRegime
export RelationalFoundations.Diagnostics.ObstructedRegime («no_strict_regime_extension»)
end AbstractSegmentedTurning.ObstructedRegime
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («ObstructedRegime»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.SegmentedBoundary.mk
export RelationalFoundations.Diagnostics.SegmentedBoundary.mk («sizeOf_spec»)
end AbstractSegmentedTurning.SegmentedBoundary.mk
namespace AbstractSegmentedTurning.CoreCoupledObstructedRegime.mk
export RelationalFoundations.Diagnostics.CoreCoupledObstructedRegime.mk («sizeOf_spec»)
end AbstractSegmentedTurning.CoreCoupledObstructedRegime.mk
namespace AbstractSegmentedTurning.CoreTurningConclusion
export RelationalFoundations.Diagnostics.CoreTurningConclusion («totalizationRejected»)
end AbstractSegmentedTurning.CoreTurningConclusion
namespace AbstractSegmentedTurning.CoreCoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoreCoupledObstructedRegime («Regime»)
end AbstractSegmentedTurning.CoreCoupledObstructedRegime
namespace AbstractSegmentedTurning.ObstructedRegime
export RelationalFoundations.Diagnostics.ObstructedRegime («Attempt»)
end AbstractSegmentedTurning.ObstructedRegime
namespace AbstractSegmentedTurning.ObstructedRegime
export RelationalFoundations.Diagnostics.ObstructedRegime («exactClassification»)
end AbstractSegmentedTurning.ObstructedRegime
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («coreCoupledTurning»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.SegmentedBoundary
export RelationalFoundations.Diagnostics.SegmentedBoundary («ctorIdx»)
end AbstractSegmentedTurning.SegmentedBoundary
namespace AbstractSegmentedTurning.CorePositiveResidualBoundary
export RelationalFoundations.Diagnostics.CorePositiveResidualBoundary («ctorIdx»)
end AbstractSegmentedTurning.CorePositiveResidualBoundary
namespace AbstractSegmentedTurning.CorePositiveResidualBoundary
export RelationalFoundations.Diagnostics.CorePositiveResidualBoundary («uniqueResidualOccurrence»)
end AbstractSegmentedTurning.CorePositiveResidualBoundary
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («RegimeExit»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.CoreTurningConclusion
export RelationalFoundations.Diagnostics.CoreTurningConclusion («continuationIsStrict»)
end AbstractSegmentedTurning.CoreTurningConclusion
namespace AbstractSegmentedTurning.PositiveResidualBoundary
export RelationalFoundations.Diagnostics.PositiveResidualBoundary («uniqueResidualOccurrence»)
end AbstractSegmentedTurning.PositiveResidualBoundary
namespace AbstractSegmentedTurning.CoreSegmentedBoundary
export RelationalFoundations.Diagnostics.CoreSegmentedBoundary («core»)
end AbstractSegmentedTurning.CoreSegmentedBoundary
namespace AbstractSegmentedTurning.CoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoupledObstructedRegime («rejectTotalization»)
end AbstractSegmentedTurning.CoupledObstructedRegime
namespace AbstractSegmentedTurning.CoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoupledObstructedRegime («admittedPositiveBoundary_rejected»)
end AbstractSegmentedTurning.CoupledObstructedRegime
namespace AbstractSegmentedTurning.CoreCoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoreCoupledTurningConclusion («continuationIsStrict»)
end AbstractSegmentedTurning.CoreCoupledTurningConclusion
namespace AbstractSegmentedTurning.SegmentedBoundary
export RelationalFoundations.Diagnostics.SegmentedBoundary («toCoreBoundary»)
end AbstractSegmentedTurning.SegmentedBoundary
namespace AbstractSegmentedTurning.PositiveResidualBoundary
export RelationalFoundations.Diagnostics.PositiveResidualBoundary («extension»)
end AbstractSegmentedTurning.PositiveResidualBoundary
namespace AbstractSegmentedTurning.PositiveResidualBoundary
export RelationalFoundations.Diagnostics.PositiveResidualBoundary («mk»)
end AbstractSegmentedTurning.PositiveResidualBoundary
namespace AbstractSegmentedTurning.RegimeExit
export RelationalFoundations.Diagnostics.RegimeExit («faithful»)
end AbstractSegmentedTurning.RegimeExit
namespace AbstractSegmentedTurning.RegimeExit
export RelationalFoundations.Diagnostics.RegimeExit («refutesFaithfulToRegime»)
end AbstractSegmentedTurning.RegimeExit
namespace AbstractSegmentedTurning.TurningConclusion
export RelationalFoundations.Diagnostics.TurningConclusion («mk»)
end AbstractSegmentedTurning.TurningConclusion
namespace AbstractSegmentedTurning.CoreTurningConclusion
export RelationalFoundations.Diagnostics.CoreTurningConclusion («continuationOutsideRegime»)
end AbstractSegmentedTurning.CoreTurningConclusion
namespace AbstractSegmentedTurning.CoreSegmentedBoundary
export RelationalFoundations.Diagnostics.CoreSegmentedBoundary («mk»)
end AbstractSegmentedTurning.CoreSegmentedBoundary
namespace AbstractSegmentedTurning.PositiveResidualBoundary
export RelationalFoundations.Diagnostics.PositiveResidualBoundary («toCoreBoundary»)
end AbstractSegmentedTurning.PositiveResidualBoundary
namespace AbstractSegmentedTurning.CoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoupledTurningConclusion («continuationIsStrict»)
end AbstractSegmentedTurning.CoupledTurningConclusion
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («ExactRegimeClassification»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.CoreSegmentedBoundary
export RelationalFoundations.Diagnostics.CoreSegmentedBoundary («positive»)
end AbstractSegmentedTurning.CoreSegmentedBoundary
namespace AbstractSegmentedTurning.CoreCoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoreCoupledObstructedRegime («continuation_outside_regime»)
end AbstractSegmentedTurning.CoreCoupledObstructedRegime
namespace AbstractSegmentedTurning.TurningConclusion
export RelationalFoundations.Diagnostics.TurningConclusion («continuationIsStrict»)
end AbstractSegmentedTurning.TurningConclusion
namespace AbstractSegmentedTurning.ObstructedRegime
export RelationalFoundations.Diagnostics.ObstructedRegime («rejectTotalization»)
end AbstractSegmentedTurning.ObstructedRegime
namespace AbstractSegmentedTurning.BoundaryGenerator
export RelationalFoundations.Diagnostics.BoundaryGenerator («continuation_ne_boundary»)
end AbstractSegmentedTurning.BoundaryGenerator
namespace AbstractSegmentedTurning.ExactRegimeClassification
export RelationalFoundations.Diagnostics.ExactRegimeClassification («mk»)
end AbstractSegmentedTurning.ExactRegimeClassification
namespace AbstractSegmentedTurning.RegimeExit
export RelationalFoundations.Diagnostics.RegimeExit («inadmissible»)
end AbstractSegmentedTurning.RegimeExit
namespace AbstractSegmentedTurning
export RelationalFoundations.Diagnostics («TurningConclusion»)
end AbstractSegmentedTurning
namespace AbstractSegmentedTurning.CoreCoupledTurningConclusion
export RelationalFoundations.Diagnostics.CoreCoupledTurningConclusion («noStrictRegimeExtension»)
end AbstractSegmentedTurning.CoreCoupledTurningConclusion
namespace AbstractSegmentedTurning.CorePositiveResidualBoundary
export RelationalFoundations.Diagnostics.CorePositiveResidualBoundary («strict»)
end AbstractSegmentedTurning.CorePositiveResidualBoundary
namespace AbstractSegmentedTurning.CorePositiveResidualBoundary
export RelationalFoundations.Diagnostics.CorePositiveResidualBoundary («mk»)
end AbstractSegmentedTurning.CorePositiveResidualBoundary
namespace AbstractSegmentedTurning.CoupledObstructedRegime
export RelationalFoundations.Diagnostics.CoupledObstructedRegime («canonicalRegime»)
end AbstractSegmentedTurning.CoupledObstructedRegime
