import Constitution.GenericCircularView
import RelationalFoundations
import SegmentedResidualRole
import AbstractSegmentedTurning
import ExactTypeTransport
import StrongPerimetralTurning
import RelationalPerimeter.Computation.EndogenousOperationalDecomposition

/-!
# Relational Perimeter

Public entry point for the four foundational modules and the computational
construction of endogenous operational decomposition.
-/

/- AXIOM_AUDIT_BEGIN -/
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.endogenous_production_and_width_separation
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.extensive_multiplicity_does_not_force_full_operational_width
#print axioms StrongPerimetralTurning.Example.examplePresentation
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.evidence
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.family
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.operationalStabilityEvidence
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutiveNormalizerSuccinctnessEvidence
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.publicBinaryExtensiveFamily
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.binary_family_exponential_width_iff_separate_preservation
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.binary_family_exponential_width_iff_carry_injective
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.binary_family_exponential_width_iff_distinct_separate_conservation
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.binary_family_exponential_width_iff_exact_separate_capacity
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutiveExtensiveSeparationEvidence
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.ExactCausalExponentialTarget
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.exactCausalExponentialTargetEvidence
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.causalOperationalExecution
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.causal_operational_execution_erases_to_authoritative
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.causal_operational_decomposition_is_prefix_local
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_normalization_consumes_constitutive_chain
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_normalization_chain_is_causally_exact
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executedConstitutiveObligationRegime
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executedConstitutiveExactOperationalRegime
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_constitutive_regime_is_exact_realization
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_source_profiles_are_distinct
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_source_profiles_are_codetermined
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_distinct_profiles_carry_together
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executedConstitutiveTarget
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executedConstitutiveTargetTrace
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_constitutive_target_exact
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_carry_eq_iff_produced_target_eq
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_carry_value_eq_produced_target
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_carry_eq_iff_operational_codetermination
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_produced_target_frontier_exact
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_causal_regime_width_eq_produced_target_width
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_regime_exponential_width_iff_separate_preservation
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_constitutive_obligation_width_is_one
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constituted_exponential_width_iff_distinct_separate_conservation
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constituted_exponential_width_iff_carry_injective
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutedDistinctSeparateRegime
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constituted_distinct_separate_regime_has_exponential_width
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constituted_distinct_separate_regime_conserves
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_reduction_does_not_preserve_separate_obligations
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.independent_profile_addressing_requires_exponential_slots
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutive_normalizer_program_code_size_exact
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutive_normalizer_code_metric_exact
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutive_normalizer_code_size_exact
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutive_normalizer_interpreter_exact
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutive_normalizer_returns_executed_codes
/- AXIOM_AUDIT_END -/
