import RelationalFoundations.Residual
set_option linter.defProp false
set_option linter.checkUnivs false
namespace SegmentedResidualRole.ContractibleRole.mk
export RelationalFoundations.Residual.ContractibleRole.mk («sizeOf_spec»)
end SegmentedResidualRole.ContractibleRole.mk
namespace SegmentedResidualRole
export RelationalFoundations.Residual («PositiveNewPart»)
end SegmentedResidualRole
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («label»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («embedNew»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («internalCompletion»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.CoreUniqueResidualOccurrence
export RelationalFoundations.Residual.CoreUniqueResidualOccurrence («occurrence»)
end SegmentedResidualRole.CoreUniqueResidualOccurrence
namespace SegmentedResidualRole.ContractibleRole
export RelationalFoundations.Residual.ContractibleRole («mk»)
end SegmentedResidualRole.ContractibleRole
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («newOccurrence_label_is_residual»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole
export RelationalFoundations.Residual («CoreUniqueResidualOccurrence»)
end SegmentedResidualRole
namespace SegmentedResidualRole
export RelationalFoundations.Residual («KernelUniqueResidualOccurrence»)
end SegmentedResidualRole
namespace SegmentedResidualRole.ExactReconstructionConditions.mk
export RelationalFoundations.Residual.ExactReconstructionConditions.mk («sizeOf_spec»)
end SegmentedResidualRole.ExactReconstructionConditions.mk
namespace SegmentedResidualRole.PositiveNewPart
export RelationalFoundations.Residual.PositiveNewPart («occurrence»)
end SegmentedResidualRole.PositiveNewPart
namespace SegmentedResidualRole
export RelationalFoundations.Residual («ResidualDeterminationCore»)
end SegmentedResidualRole
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («label»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole
export RelationalFoundations.Residual («positiveExtension_hasUniqueResidualOccurrence»)
end SegmentedResidualRole
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («reconstructed_occurrenceToRole_agrees»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.ExactInternalCompletion
export RelationalFoundations.Residual.ExactInternalCompletion («ctorIdx»)
end SegmentedResidualRole.ExactInternalCompletion
namespace SegmentedResidualRole
export RelationalFoundations.Residual («positiveExtension_result_occurrence»)
end SegmentedResidualRole
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («embedOld_injective»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («embedNewInjective»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.ResidualDeterminationCore
export RelationalFoundations.Residual.ResidualDeterminationCore («noInternalReuse»)
end SegmentedResidualRole.ResidualDeterminationCore
namespace SegmentedResidualRole.UniqueResidualOccurrence
export RelationalFoundations.Residual.UniqueResidualOccurrence («occurrence»)
end SegmentedResidualRole.UniqueResidualOccurrence
namespace SegmentedResidualRole.ContractibleRole
export RelationalFoundations.Residual.ContractibleRole («contracts»)
end SegmentedResidualRole.ContractibleRole
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («preservesInternal»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole
export RelationalFoundations.Residual («UniqueResidualOccurrence»)
end SegmentedResidualRole
namespace SegmentedResidualRole.FaithfulExtension.mk
export RelationalFoundations.Residual.FaithfulExtension.mk («sizeOf_spec»)
end SegmentedResidualRole.FaithfulExtension.mk
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («toDeterminationCore»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole
export RelationalFoundations.Residual («positiveKernel_hasUniqueResidualOccurrence»)
end SegmentedResidualRole
namespace SegmentedResidualRole.ContractibleRole
export RelationalFoundations.Residual.ContractibleRole («ctorIdx»)
end SegmentedResidualRole.ContractibleRole
namespace SegmentedResidualRole.KernelUniqueResidualOccurrence.mk
export RelationalFoundations.Residual.KernelUniqueResidualOccurrence.mk («sizeOf_spec»)
end SegmentedResidualRole.KernelUniqueResidualOccurrence.mk
namespace SegmentedResidualRole.PositiveNewPart.mk
export RelationalFoundations.Residual.PositiveNewPart.mk («sizeOf_spec»)
end SegmentedResidualRole.PositiveNewPart.mk
namespace SegmentedResidualRole.ResidualUniquenessKernel.mk
export RelationalFoundations.Residual.ResidualUniquenessKernel.mk («sizeOf_spec»)
end SegmentedResidualRole.ResidualUniquenessKernel.mk
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («embedOld»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.ExactInternalCompletion
export RelationalFoundations.Residual.ExactInternalCompletion («occurrenceToRole_pointwise_unique»)
end SegmentedResidualRole.ExactInternalCompletion
namespace SegmentedResidualRole.ResidualDeterminationCore
export RelationalFoundations.Residual.ResidualDeterminationCore («ctorIdx»)
end SegmentedResidualRole.ResidualDeterminationCore
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («reconstructInternalCompletion»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.ExactInternalCompletion
export RelationalFoundations.Residual.ExactInternalCompletion («occurrenceRoundTrip»)
end SegmentedResidualRole.ExactInternalCompletion
namespace SegmentedResidualRole.ExactReconstructionConditions
export RelationalFoundations.Residual.ExactReconstructionConditions («toExactInternalCompletion»)
end SegmentedResidualRole.ExactReconstructionConditions
namespace SegmentedResidualRole.KernelUniqueResidualOccurrence
export RelationalFoundations.Residual.KernelUniqueResidualOccurrence («mk»)
end SegmentedResidualRole.KernelUniqueResidualOccurrence
namespace SegmentedResidualRole.ResidualDeterminationCore
export RelationalFoundations.Residual.ResidualDeterminationCore («newLabelInjective»)
end SegmentedResidualRole.ResidualDeterminationCore
namespace SegmentedResidualRole.ExactInternalCompletion
export RelationalFoundations.Residual.ExactInternalCompletion («roleRoundTrip»)
end SegmentedResidualRole.ExactInternalCompletion
namespace SegmentedResidualRole.CoreUniqueResidualOccurrence
export RelationalFoundations.Residual.CoreUniqueResidualOccurrence («mk»)
end SegmentedResidualRole.CoreUniqueResidualOccurrence
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («newOccurrence_label_is_residual»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («embedNewInjective»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole.CoreUniqueResidualOccurrence
export RelationalFoundations.Residual.CoreUniqueResidualOccurrence («toRich»)
end SegmentedResidualRole.CoreUniqueResidualOccurrence
namespace SegmentedResidualRole.ExactReconstructionConditions
export RelationalFoundations.Residual.ExactReconstructionConditions («embedOldInjective»)
end SegmentedResidualRole.ExactReconstructionConditions
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («toExactInternalCompletion_of_positive»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («newOccurrences_unique»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole
export RelationalFoundations.Residual («ExactReconstructionConditions»)
end SegmentedResidualRole
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («reconstructed_roleToOccurrence_eq»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («labelFaithful»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole.ExactInternalCompletion
export RelationalFoundations.Residual.ExactInternalCompletion («mk»)
end SegmentedResidualRole.ExactInternalCompletion
namespace SegmentedResidualRole
export RelationalFoundations.Residual («ExactInternalRealization»)
end SegmentedResidualRole
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («oldNewDisjoint»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole.UniqueResidualOccurrence
export RelationalFoundations.Residual.UniqueResidualOccurrence («labelIsResidual»)
end SegmentedResidualRole.UniqueResidualOccurrence
namespace SegmentedResidualRole.ExactInternalCompletion
export RelationalFoundations.Residual.ExactInternalCompletion («occurrenceToRole»)
end SegmentedResidualRole.ExactInternalCompletion
namespace SegmentedResidualRole.CoreUniqueResidualOccurrence
export RelationalFoundations.Residual.CoreUniqueResidualOccurrence («labelIsResidual»)
end SegmentedResidualRole.CoreUniqueResidualOccurrence
namespace SegmentedResidualRole
export RelationalFoundations.Residual («FaithfulExtension»)
end SegmentedResidualRole
namespace SegmentedResidualRole.ExactReconstructionConditions
export RelationalFoundations.Residual.ExactReconstructionConditions («oldLabelsInternal»)
end SegmentedResidualRole.ExactReconstructionConditions
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («labelFaithful»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («mk»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole.ResidualDeterminationCore
export RelationalFoundations.Residual.ResidualDeterminationCore («newLabel»)
end SegmentedResidualRole.ResidualDeterminationCore
namespace SegmentedResidualRole.KernelUniqueResidualOccurrence
export RelationalFoundations.Residual.KernelUniqueResidualOccurrence («unique»)
end SegmentedResidualRole.KernelUniqueResidualOccurrence
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («embedNew»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.ExactInternalRealization
export RelationalFoundations.Residual.ExactInternalRealization («ctorIdx»)
end SegmentedResidualRole.ExactInternalRealization
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («newOccurrences_unique»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole.ExactInternalCompletion.mk
export RelationalFoundations.Residual.ExactInternalCompletion.mk («sizeOf_spec»)
end SegmentedResidualRole.ExactInternalCompletion.mk
namespace SegmentedResidualRole.ContractibleRole
export RelationalFoundations.Residual.ContractibleRole («center»)
end SegmentedResidualRole.ContractibleRole
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («toResidualUniquenessKernel»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («newOccurrence_cannotReuseInternalRole»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.ExactReconstructionConditions
export RelationalFoundations.Residual.ExactReconstructionConditions («mk»)
end SegmentedResidualRole.ExactReconstructionConditions
namespace SegmentedResidualRole.UniqueResidualOccurrence
export RelationalFoundations.Residual.UniqueResidualOccurrence («mk»)
end SegmentedResidualRole.UniqueResidualOccurrence
namespace SegmentedResidualRole.UniqueResidualOccurrence.mk
export RelationalFoundations.Residual.UniqueResidualOccurrence.mk («sizeOf_spec»)
end SegmentedResidualRole.UniqueResidualOccurrence.mk
namespace SegmentedResidualRole
export RelationalFoundations.Residual («positiveCore_hasUniqueResidualOccurrence»)
end SegmentedResidualRole
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («roleToOccurrence»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole.KernelUniqueResidualOccurrence
export RelationalFoundations.Residual.KernelUniqueResidualOccurrence («ctorIdx»)
end SegmentedResidualRole.KernelUniqueResidualOccurrence
namespace SegmentedResidualRole.ResidualDeterminationCore
export RelationalFoundations.Residual.ResidualDeterminationCore («occurrences_unique»)
end SegmentedResidualRole.ResidualDeterminationCore
namespace SegmentedResidualRole
export RelationalFoundations.Residual («ExactInternalCompletion»)
end SegmentedResidualRole
namespace SegmentedResidualRole.ExactInternalRealization.mk
export RelationalFoundations.Residual.ExactInternalRealization.mk («sizeOf_spec»)
end SegmentedResidualRole.ExactInternalRealization.mk
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («embedOld»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole.ResidualDeterminationCore
export RelationalFoundations.Residual.ResidualDeterminationCore («mk»)
end SegmentedResidualRole.ResidualDeterminationCore
namespace SegmentedResidualRole.ExactInternalRealization
export RelationalFoundations.Residual.ExactInternalRealization («occurrenceRoundTrip»)
end SegmentedResidualRole.ExactInternalRealization
namespace SegmentedResidualRole.CoreUniqueResidualOccurrence
export RelationalFoundations.Residual.CoreUniqueResidualOccurrence («ctorIdx»)
end SegmentedResidualRole.CoreUniqueResidualOccurrence
namespace SegmentedResidualRole
export RelationalFoundations.Residual («ContractibleRole»)
end SegmentedResidualRole
namespace SegmentedResidualRole.CoreUniqueResidualOccurrence.mk
export RelationalFoundations.Residual.CoreUniqueResidualOccurrence.mk («sizeOf_spec»)
end SegmentedResidualRole.CoreUniqueResidualOccurrence.mk
namespace SegmentedResidualRole.UniqueResidualOccurrence
export RelationalFoundations.Residual.UniqueResidualOccurrence («unique»)
end SegmentedResidualRole.UniqueResidualOccurrence
namespace SegmentedResidualRole
export RelationalFoundations.Residual («ResidualUniquenessKernel»)
end SegmentedResidualRole
namespace SegmentedResidualRole.ResidualDeterminationCore
export RelationalFoundations.Residual.ResidualDeterminationCore («label_is_residual»)
end SegmentedResidualRole.ResidualDeterminationCore
namespace SegmentedResidualRole.CoreUniqueResidualOccurrence
export RelationalFoundations.Residual.CoreUniqueResidualOccurrence («unique»)
end SegmentedResidualRole.CoreUniqueResidualOccurrence
namespace SegmentedResidualRole.ExactInternalCompletion
export RelationalFoundations.Residual.ExactInternalCompletion («toExactInternalRealization»)
end SegmentedResidualRole.ExactInternalCompletion
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («mk»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.PositiveNewPart
export RelationalFoundations.Residual.PositiveNewPart («ctorIdx»)
end SegmentedResidualRole.PositiveNewPart
namespace SegmentedResidualRole
export RelationalFoundations.Residual («OldLabelsInternal»)
end SegmentedResidualRole
namespace SegmentedResidualRole.ExactInternalRealization
export RelationalFoundations.Residual.ExactInternalRealization («roleRoundTrip»)
end SegmentedResidualRole.ExactInternalRealization
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («newOccurrence_cannotReuseInternalRole»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole.CoreUniqueResidualOccurrence
export RelationalFoundations.Residual.CoreUniqueResidualOccurrence («toKernel»)
end SegmentedResidualRole.CoreUniqueResidualOccurrence
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («reconstructed_roleToOccurrence_agrees»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («oldLabelsInternal_of_positive»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole.KernelUniqueResidualOccurrence
export RelationalFoundations.Residual.KernelUniqueResidualOccurrence («occurrence»)
end SegmentedResidualRole.KernelUniqueResidualOccurrence
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («ctorIdx»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.ExactReconstructionConditions
export RelationalFoundations.Residual.ExactReconstructionConditions («ctorIdx»)
end SegmentedResidualRole.ExactReconstructionConditions
namespace SegmentedResidualRole.ResidualDeterminationCore.mk
export RelationalFoundations.Residual.ResidualDeterminationCore.mk («sizeOf_spec»)
end SegmentedResidualRole.ResidualDeterminationCore.mk
namespace SegmentedResidualRole.ExactInternalRealization
export RelationalFoundations.Residual.ExactInternalRealization («roleToOccurrence»)
end SegmentedResidualRole.ExactInternalRealization
namespace SegmentedResidualRole.PositiveNewPart
export RelationalFoundations.Residual.PositiveNewPart («mk»)
end SegmentedResidualRole.PositiveNewPart
namespace SegmentedResidualRole.KernelUniqueResidualOccurrence
export RelationalFoundations.Residual.KernelUniqueResidualOccurrence («labelIsResidual»)
end SegmentedResidualRole.KernelUniqueResidualOccurrence
namespace SegmentedResidualRole.ExactInternalCompletion
export RelationalFoundations.Residual.ExactInternalCompletion («toReconstructionConditions»)
end SegmentedResidualRole.ExactInternalCompletion
namespace SegmentedResidualRole.ResidualUniquenessKernel
export RelationalFoundations.Residual.ResidualUniquenessKernel («ctorIdx»)
end SegmentedResidualRole.ResidualUniquenessKernel
namespace SegmentedResidualRole.ExactInternalRealization
export RelationalFoundations.Residual.ExactInternalRealization («mk»)
end SegmentedResidualRole.ExactInternalRealization
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («preservesInternal»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.UniqueResidualOccurrence
export RelationalFoundations.Residual.UniqueResidualOccurrence («ctorIdx»)
end SegmentedResidualRole.UniqueResidualOccurrence
namespace SegmentedResidualRole.FaithfulExtension
export RelationalFoundations.Residual.FaithfulExtension («oldNewDisjoint»)
end SegmentedResidualRole.FaithfulExtension
namespace SegmentedResidualRole.ExactInternalRealization
export RelationalFoundations.Residual.ExactInternalRealization («occurrenceToRole»)
end SegmentedResidualRole.ExactInternalRealization
