import RelationalPerimeter.Relativity.Reconstruction.LocalizedPresentations

/-!
# Agreement generated by an executed local encounter

The generating passage consumes a stored production admitted by the coupling
formation. It relates its two participants; it cannot start from a bare
numerical coincidence or an independently supplied shared point. Exact
description changes have returns. Neither source identity nor forgetting
attached effects is a constructor or consequence of this agreement.
-/
set_option genInjectivity false
namespace RelationalPerimeter.Relativity.Reconstruction
open RelationalPerimeter.Relativity.Production
open RelationalPerimeter.Relativity.Production.Encounter
open ConstitutiveSearch.Resources

inductive LocationAgreement {source admitted} (production : EncounterProduction source admitted) :
    {current target : RecurringCursor} → LocalizedPresentation production current →
      LocalizedPresentation production target → Type where
  | encounter (one two : Port) :
      LocationAgreement production (localizeParticipant production one) (localizeParticipant production two)
  | carried {current} (path : DescriptionPath production.head.successor current) (one two : Port) :
      LocationAgreement production ⟨one, path⟩ ⟨two, path⟩
  | identity {current} (presentation : LocalizedPresentation production current) :
      LocationAgreement production presentation presentation
  | change {current target} (presentation : LocalizedPresentation production current)
      (raccord : AddressedRecurringRaccord current target) :
      LocationAgreement production presentation (presentation.reexpress raccord)
  | reverse {current target} {one : LocalizedPresentation production current}
      {two : LocalizedPresentation production target} (agreement : LocationAgreement production one two) :
      LocationAgreement production two one
  | compose {current middle target} {one : LocalizedPresentation production current}
      {two : LocalizedPresentation production middle} {three : LocalizedPresentation production target}
      (first : LocationAgreement production one two) (second : LocationAgreement production two three) :
      LocationAgreement production one three

def LocationAgreement.site {source admitted production current target}
    {one : @LocalizedPresentation source admitted production current}
    {two : @LocalizedPresentation source admitted production target}
    (agreement : LocationAgreement production one two) :
    InteractionSiteAgreement one.attachment two.attachment :=
  match agreement with
  | .encounter one two => by
      cases one <;> cases two <;> exact ⟨.identity _, rfl⟩
  | .carried path one two => by
      cases one <;> cases two <;> exact ⟨.identity _, rfl⟩
  | .identity presentation => .identity presentation.attachment
  | .change presentation raccord => by
      rcases presentation with ⟨participant, path⟩
      cases participant with
      | left => exact .reexpression (InteractionAttachment.first production.head path) raccord
      | right => exact .reexpression (InteractionAttachment.second production.head path) raccord
  | .reverse previous => previous.site.reverse
  | .compose first second => first.site.compose second.site
termination_by structural agreement

theorem location_agreement_exact {source admitted production current target}
    {one : @LocalizedPresentation source admitted production current}
    {two : @LocalizedPresentation source admitted production target}
    (agreement : LocationAgreement production one two) :
    agreement.site.raccord.constitution.references.forward one.location = two.location := agreement.site.anchorExact

def producedLocationAgreement {source admitted} (production : EncounterProduction source admitted) :
    LocationAgreement production (localizeParticipant production .left) (localizeParticipant production .right) :=
  .encounter .left .right

/-- The common local description is the actual interaction occurrence on its
constituted support, not the constant response of an instrument. -/
def commonEncounterLocation {source admitted} (production : EncounterProduction source admitted) :
    Ref production.head.successor.kinds .reading := comparisonAnchor production.head

theorem participants_have_common_location {source admitted} (production : EncounterProduction source admitted) :
    (localizeParticipant production .left).location = commonEncounterLocation production ∧
      (localizeParticipant production .right).location = commonEncounterLocation production := ⟨rfl, rfl⟩

theorem common_location_is_not_an_arrival {source admitted} (production : EncounterProduction source admitted) :
    commonEncounterLocation production ≠ production.first.readingReference :=
  attached_anchor_not_arrival production.first

theorem agreed_sources_are_distinct {source admitted} (production : EncounterProduction source admitted) :
    Nonempty (LocationAgreement production (localizeParticipant production .left) (localizeParticipant production .right)) ∧
      (localizeParticipant production .left).attachment.readingReference ≠
        (localizeParticipant production .right).attachment.readingReference := by
  -- Keep the positive agreement as data; this theorem concerns existence.
  exact ⟨⟨producedLocationAgreement production⟩, localized_sources_distinct production⟩

theorem agreement_preserves_distinct_effects {source admitted} (production : EncounterProduction source admitted)
    (different : production.effects.1 ≠ production.effects.2) :
    (localizeParticipant production .left) ≠ (localizeParticipant production .right) :=
  differing_effects_distinguish_presentations _ _ different

def continuedLocationAgreement {source admitted} (production : EncounterProduction source admitted)
    {target : State} (history : Encounter.History production.next target) :
    LocationAgreement production
      ((localizeParticipant production .left).prolong history)
      ((localizeParticipant production .right).prolong history) := by
  -- Both paths consume the same stored suffix. Its preserved interaction is
  -- the old encounter; this does not colocate the participants' future events.
  exact .carried (history.describe .root) .left .right

end RelationalPerimeter.Relativity.Reconstruction
/- AXIOM_AUDIT_BEGIN -/
#print axioms RelationalPerimeter.Relativity.Reconstruction.LocationAgreement
#print axioms RelationalPerimeter.Relativity.Reconstruction.LocationAgreement.site
#print axioms RelationalPerimeter.Relativity.Reconstruction.location_agreement_exact
#print axioms RelationalPerimeter.Relativity.Reconstruction.producedLocationAgreement
#print axioms RelationalPerimeter.Relativity.Reconstruction.participants_have_common_location
#print axioms RelationalPerimeter.Relativity.Reconstruction.common_location_is_not_an_arrival
#print axioms RelationalPerimeter.Relativity.Reconstruction.agreed_sources_are_distinct
#print axioms RelationalPerimeter.Relativity.Reconstruction.agreement_preserves_distinct_effects
#print axioms RelationalPerimeter.Relativity.Reconstruction.continuedLocationAgreement
/- AXIOM_AUDIT_END -/
