import SegmentedResidualRole
import AbstractSegmentedTurning
import ExactTypeTransport
import StrongPerimetralTurning
import RelationalPerimeter.Computation.EndogenousOperationalDecomposition

/-!
# Relational Perimeter

Public entry point for the four foundational modules and the computational
construction of endogenous operational decomposition.
-/

/- AXIOM_AUDIT_BEGIN -/
#print axioms StrongPerimetralTurning.Example.examplePresentation
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.evidence
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.family
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.operationalStabilityEvidence
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutiveNormalizerSuccinctnessEvidence
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.publicBinaryExtensiveFamily
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.binary_family_exponential_width_iff_separate_preservation
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.binary_family_exponential_width_iff_distinct_separate_conservation
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.binary_family_exponential_width_iff_exact_separate_capacity
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutiveExtensiveSeparationEvidence
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constituted_exponential_width_iff_distinct_separate_conservation
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutedDistinctSeparateRegime
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constituted_distinct_separate_regime_has_exponential_width
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constituted_distinct_separate_regime_conserves
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.executed_reduction_does_not_preserve_separate_obligations
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.independent_profile_addressing_requires_exponential_slots
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutive_normalizer_program_code_size_exact
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutive_normalizer_code_metric_exact
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutive_normalizer_code_size_exact
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutive_normalizer_interpreter_exact
#print axioms RelationalPerimeter.Computation.EndogenousOperationalDecomposition.constitutive_normalizer_returns_executed_codes
/- AXIOM_AUDIT_END -/
