$ErrorActionPreference = 'Stop'
$taskDirectory = $PSScriptRoot
$repositoryDirectory = [IO.Path]::GetFullPath((Join-Path $taskDirectory '../../..'))
$knowledgeFile = Join-Path $repositoryDirectory 'labyrinth/knowledge.json'
$knowledgeData = Get-Content -LiteralPath $knowledgeFile -Raw | ConvertFrom-Json

# Format: id | role in relational priority | received | constructed | readout | scope | correction.
$assessmentRows = @'
src.main|Archive du socle qui constitue les positions et les occurrences avant leurs lectures.|Sources et façade de la base 8a5e494, snapshots et contrôles antérieurs.|Architecture historique déjà formalisée ; cette fiche n'ajoute aucune construction.|Ancres de la base et état courant distingués ; l'archive ne vaut pas nouvelle validation.|Provenance historique des quatre modules ; hors certification nouvelle du dépôt.|Conserver l'archive et placer ses résultats intérieurs au centre de la nouvelle lecture ; ne pas changer le tier de leurs nœuds.
src.plan|Programme de constitution relationnelle, explicitement distinct du code acquis.|Texte conceptuel utilisateur, choix proposés et référence documentaire locale.|Interfaces schématiques et critères futurs, pas des théorèmes compilés par ce document.|La convention 0-types décrit les identités ; elle ne postule pas une extension d'unités primitivement individuées.|Programme relatif à une présentation ; statut documentaire et prospectif.|Confirmer son statut de proposition ; remplacer toute lecture extensionnelle par relations, places, occurrences, domaine exact puis nombre éventuel.
m.presentation|Les configurations nodales sont relationnelles et les avancées témoignées constituent les places.|Sortes-supports, familles, nœuds équipés, épine positive et jonction ; obstruction séparée.|Positions here/later sur les avancées et couches de présentation raccordées.|Nœuds et jonction peuvent être lus ; ces lectures ne constituent pas une occurrence intérieure.|Architecture relative aux primitives reçues ; pas auto-engendrement de toutes les sortes.|Reformuler la note : la réception des primitives permet la constitution inductive des places ; elle n'est pas une objection à la priorité relationnelle.
m.core|Facteur logique de l'unicité, obtenu après oubli de l'architecture intérieure riche.|Étiquetage nouveau injectif, exclusion intérieure, rôle contractile.|Détermination de l'étiquette résiduelle et unicité des nouvelles occurrences.|Anciennes occurrences et inverse intérieur sont absents du noyau ; ce manque est un oubli délibéré.|Noyau abstrait de segmentation ; aucune description exhaustive du périmètre.|Confirmer et situer après l'intérieur exact, sans confondre dépendance logique minimale et constitution complète.
m.history|L'occurrence tient son identité de l'histoire composable, avant la valeur de son pas.|Famille Step et témoins concrets ; générateur historique et racine pour RootedGeneratedHistory.|Histoires dépendantes, occurrences last/earlier et raccord des pas.|Lectures source/cible/curseur après constitution ; leur codomaine ne remplace pas l'histoire.|Histoire générique et instance canonique à distinguer.|Mettre au premier plan l'individuation par construction ; conserver la réserve sur le graphe de dépendances sélectionnées.
th.residual|Une partie nouvelle déjà constituée se détermine dans une classification fidèle.|Rôle contractile, exclusion intérieure, injectivité ; habitant supplémentaire pour le centre nouveau.|Étiquette résiduelle puis sous-singleton ; positivité donne un témoin unique.|Le label lit une occurrence ; il ne la crée pas. label_is_residual n'utilise pas l'injectivité.|T2 abstrait conditionnel au noyau ; pas clôture ou génération universelle.|Confirmer le T2 et séparer le label, l'unicité et l'habitation ; ne pas lire ce noyau comme origine de l'intérieur.
th.internal-reconstruction|Le domaine ancien exact est reconstruit à partir d'un placement et d'accords précis.|ResidualUniquenessKernel, nouvelle partie positive, injectivité de embedOld.|Internalité des labels anciens, inverse occurrenceToRole et deux retours.|L'inverse du même placement est unique point par point ; toutes les réalisations possibles ne sont pas identifiées.|T2 de reconstruction relative à un noyau fixé.|Confirmer et préserver l'injectivité ancienne ; présenter cette reconstruction comme acquis positif sur l'intérieur.
th.abstract-exit|Le statut d'une continuation constituée change selon une admission supplémentaire.|Générateur avec extension irréflexive ; frontière admise ; analyse canonique-ou-tentative ; rejet.|Classification exacte du régime puis continuation hors régime.|Le diagnostic conserve le candidat ; sa non-admission n'annule pas sa constitution.|T2 conditionnel au régime explicite, indépendant d'une circularité universelle.|Confirmer ; citer précisément classifyOrTotalize et rejectTotalization comme hypothèses de sortie.
th.transport-backward|Les retours exacts permettent une reconstruction inverse pour des applications déjà choisies.|Deux transports exacts et accord ponctuel des cartes directes.|Accord ponctuel de leurs cartes inverses.|Les porteurs sont comparés ; aucune conservation relationnelle n'est incluse par défaut.|T2 neutre, appliqué ensuite aux interfaces équipées.|Confirmer ; ne pas confondre cet oubli des relations avec la nature fondationnelle des objets comparés.
th.perimeter-exact|Résultat central : le domaine intérieur des places est exactement réalisé par les occurrences engendrées.|Présentation relationnelle et déploiement canonique de ses jonctions successives.|Deux applications positions-occurrences et deux retours, avec accords canoniques associés.|Les occurrences de ce déploiement sont toutes décodées ; le témoin fermant n'est pas parcouru.|T2 sur le déploiement intérieur de la même présentation.|Mettre ce résultat au centre ; ajouter que le domaine exact est constitué avant sa lecture numérique.
th.rooted-structure|La composition réelle permet de reconstruire les relations entre unités constituées.|ExactNonClosingRealization dans RootedGeneratedHistory ; seul sourceCursorExact est reçu par l'accord.|sourceStateExact, locatedStepExact, targetStateExact puis injectivité, précédence et succession immédiate.|Le curseur est une adresse structurale dans cette génération canonique ; pas un rang numérique arbitraire.|T2 spécialisé au générateur historique, à l'enracinement et la composabilité.|Corriger hypotheses : les accords source/cible/pas sont dérivés, pas reçus indépendamment ; préserver les trois théorèmes.
th.factorization|La couverture des places internes reconstruit un facteur initial réellement composé.|Réalisation locale exacte dans une histoire enracinée de pas canoniques.|Continuation et égalité de recomposition depuis le périmètre canonique.|Le suffixe peut être vide ; réalisation de tous les rôles internes ne couvre pas forcément toute histoire cible.|T2 dans RootedGeneratedHistory ; pas converse de toute trace.|Confirmer et associer explicitement à la constitution du domaine intérieur ; garder la possibilité du suffixe vide.
th.positive-continuation|Le tout intérieur constitué n'épuise pas la génération endogène.|Présentation historique et générateur canonique disponible au terme.|Un pas effectif, histoire à un pas, extension stricte distincte du déploiement.|La continuation est extérieure à ce périmètre, pas à toute constitution possible.|T2 de l'instance historique ; continuation effectivement choisie.|Confirmer et distinguer intérieur complet, prolongement constitué et admission du prolongement.
th.no-return|La distinction de sources et cibles provient de la progression constitutive historique.|History.Positive sur GeneratedStep et PositiveConstitution canoniques.|Avancée stricte des curseurs et inégalité des états source/cible.|Des valeurs nodales brutes peuvent se répéter malgré la distinction des constitutions.|T2 de génération libre canonique ; pas non-cyclicité de tout Step.|Confirmer ; ne pas exporter la loi au PositiveHistory générique ni la confondre avec séparation des pôles.
th.labelled-residual|Une continuation constituée et fidèlement étiquetée ne réutilise pas les places intérieures déjà réalisées.|Extension recomposable, label injectif préservant les anciennes positions, résidu contractile ; positivité pour habiter.|Exclusion intérieure, label final et unicité de la partie nouvelle via segmentation.|La détermination du label n'est pas un nouveau témoin arbitraire RealizesFull ; le chemin canonique à un pas a une autre source d'unicité.|T2 dans les extensions fidèlement classées du même système de rôles.|Confirmer ; garder séparés preuve générale de segmentation et noyau direct utilisant ExactlyOne.
th.circular-classification|La maximalité est un statut d'admission du périmètre déjà constitué.|CircularRefinement : extension, fidélité, accords intérieurs, realizesFinal ; obstruction héritée.|Équivalence constructive avec le déploiement canonique et non-admission du premier pas supplémentaire.|Le même générateur continue ; finalJunction seul ne fournit pas realizesFinal.|T2 relatif à ce régime obstrué.|Confirmer et faire apparaître realizesFinal comme obligation indépendante qui produit la tentative bilatérale.
th.specification|La même constitution reçoit deux interfaces distinctes de statut.|Spécification locale avec clause trajectorielle ; régime de raffinement et obstruction au TotalLoop.|Passages soundness et complétude entre témoins de satisfaction et raffinement.|La même classification d'histoires n'identifie pas les structures de régime et de spécification.|T2 sur les signatures historiques explicites.|Confirmer ; la sortie de spécification repose sur sa clause trajectorielle, pas sur seule circularité positive.
th.turning|Le certificat réunit l'intérieur exact et la continuation dans un cadre de changement de régime.|Présentation avec architecture positive, pôles et obstruction.|Génération, déploiement exact, absorption des parties, interprétations et rejets via producteurs existants.|L'assemblage ne prouve pas à lui seul nécessité causale de chaque champ ; les accords de la chaîne doivent être suivis.|T2 sur CircularPresentation obstruée ; pas théorème universel de toute relation.|Confirmer et raconter d'abord le domaine intérieur puis le prolongement et son statut conditionnel.
th.numeric-readout|La longueur lit une quantité déjà structurée par occurrences et relations.|Histoire PerimetrallyAdmissible du même périmètre.|Préfixe constitué puis monotonie de History.length et borne numérique.|Le naturel oublie identité, liens et témoins ; il ne définit pas les occurrences ni leur ordre.|T2 de lecture dérivée ; pas définition primitive de quantité structurelle.|Confirmer et remplacer tout récit cardinal premier par constitution du domaine exact suivie de sa mesure.
th.concrete-interpretation|Une histoire constituée peut être interprétée sans perdre l'individuation de ses occurrences.|Algèbre de continuation concrète, lectures et accords primitifs des pas.|Histoire concrète et deux retours d'occurrences par induction.|Les lectures d'états/interfaces ne sont pas toutes injectives ; exactitude d'occurrences ne vaut pas équivalence entière des données.|T2 conditionnel à ConcreteContinuationAlgebra ; pas validation computationnelle.|Confirmer ; situer les lectures appauvries et réserver la fidélité des cibles à une hypothèse propre.
th.separator-order|Une projection qui oublie la composition globale peut perdre une relation constitutive.|SemanticTrace affaiblie de l'exemple et permutation des pas localement exacts.|Réalisation injective locale avec inversion des deux premières adresses.|La liste expérimentale et ses indices oublient l'enracinement/composition ; ce n'est pas l'intérieur fort.|T2 de contre-modèle précis sur la trace à quatre nœuds.|Confirmer le séparateur ; il justifie la portée du théorème fort, pas une insuffisance de l'intérieur constitué.
th.separator-bridge|Même une lecture ordonnée ne restitue pas la participation au tout composable.|Trace intercalée, accords locaux et ordre des images canoniques.|Ordre préservé et impossibilité du pont effectif entre exigences adjacentes de l'exemple.|Les occurrences intercalaires restent individuellement présentes ; leur ordre n'est pas une composition typée.|T2 de contre-modèle de trace affaiblie.|Confirmer ; placer en regard de la reconstruction positive de succession immédiate dans RootedGeneratedHistory.
th.separator-injectivity|Le résidu contractile ne détermine pas les unités nouvelles si la fidélité du label est oubliée.|Porteur nouveau Bool, résidu Unit, intérieur Empty, label constant.|Deux occurrences distinctes partageant le même label, non-injectivité.|L'égalité de lecture de rôle ne devient pas égalité d'occurrences.|T2 de modèle du noyau affaibli sans injectivité.|Confirmer ; la nécessité testée concerne l'injectivité dans cette inférence, pas toute axiomatisation possible.
th.separator-transport|Une correspondance de porteurs peut oublier une relation structurale choisie.|Transport Bool.not avec retours ; relation Before false true.|Réfutation de la conservation de Before pour ces applications.|Les retours du porteur ne contiennent aucune loi d'ordre.|T2 de contre-modèle à une inférence sur transport nu.|Confirmer ; ne pas appeler cette correspondance un transport constitutif riche.
th.final-role-carrier|Diagnostic d'une projection du rôle, qui ne décrit pas toute sa constitution équipée.|Type historique FinalRequirement à un constructeur et parent P comme paramètre.|Transport uniforme exact vers Unit.|Le porteur nu ne transporte ni jonction, ni occurrence, ni lois de frontière ; l'index peut rester un paramètre de l'équivalence.|T2 de porteur nu ; aucune réfutation de la famille équipée.|Confirmer ; préciser que l'oubli des données et lois, non la seule existence d'Unit, limite cette lecture.
x.local-order|Limite d'une donnée locale après oubli du tout composable.|Modèle permuté de SemanticTrace.|Réfutation du transfert de l'ordre depuis la seule exactitude locale.|Le carrier fort garde les données qui permettent de reconstruire l'ordre.|Voie réfutée dans la signature affaiblie, pas sur toute histoire relationnelle.|Conserver et rattacher au séparateur-order et au résultat positif rooted-structure.
x.order-bridge|Limite de la précédence lue sans raccord constitutif complet.|Modèle intercalé ordonné.|Réfutation ordre seul implique participation composable.|Un intervalle ordonné ne fournit pas son histoire-pont et sa couverture exacte.|Voie réfutée sur SemanticTrace.|Conserver en indiquant l'oubli de composition, sans affaiblir le résultat intérieur canonique.
x.weak-unique|La classification nouvelle doit rester fidèle aux occurrences.|Label constant sur deux Bool, résidu contractile et exclusion intérieure.|Réfutation de l'unicité sans injectivité.|Le résidu lu ne fusionne pas les occurrences constituées.|Voie réfutée pour noyau privé de newLabelInjective.|Conserver avec une leçon limitée à cette suppression, pas une minimalité globale.
x.exact-order|La conservation des relations est une obligation différente des retours de porteurs.|Bool.not et Before.|Réfutation de conservation automatique de toute relation par ExactTypeTransport.|Transport nu oublie la relation choisie.|Voie réfutée sur une signature neutre.|Conserver et mettre les transports riches déjà construits en regard.
q.positive-circle|La circularité positive précède les obligations d'obstruction.|Chaîne relationnelle positive, jonction et enrichissements de pôles distincts.|Séparation positive/obstruction et pont historique avec quatre retours déjà réalisés.|Aucune occurrence périodique ni rejet de toute clôture déduit du parent positif.|Question répondue dans ces données, pas généralisation totale des formations.|Confirmer answered ; l'algèbre positive est traitée ailleurs et ne doit pas redevenir une dette de cette fiche.
q.equipped-final-role|Le rôle final lit la même frontière relationnelle et le même choix que la présentation.|Forme, fibre, choix reçu ; grammaire intérieure/finale sur ce parent.|Unicité par choix, classification exacte et transports des données déjà réalisés.|La somme avec Unit classe cette grammaire ; le parent restitue les témoins ; elle ne classe pas une extension arbitraire.|Acquis T2 relatifs au parent ; extensions de rigidité/minimalité séparées.|Marquer le rôle équipé acquis ; minimalité universelle optionnelle et non condition préalable à l'exhaustivité intérieure.
q.rich-transport|La comparaison constitutive exige familles, témoins et opérations, au-delà du porteur.|Cartes exactes de toutes les fibres et accords des choix ; formation source.|Calcul dépendant, épines, positions, relations et reconstruction sur mêmes State/Step déjà réalisés.|Step entier gardé dans histoires ; données de pôles/obstruction et formations arbitraires non comparées.|Question partiellement répondue dans la signature et la reconstruction définies.|Confirmer les acquis et localiser précisément les extensions ; ne pas dire qu'il manque encore tout transport relationnel.
q.rigidity|La réalisation doit être distinguée de l'unicité de toute réalisation admissible.|Famille Realizes et décomposition choisie à préciser pour la généralisation.|L'instance historique dérive déjà l'injectivité et ses accords depuis le curseur ; inverse d'un placement fixé unique.|Deux retours n'imposent pas seuls rigidité d'une relation Realizes arbitraire.|Question ouverte générale, acquise partiellement dans l'instance forte.|Reformuler à partir de ces acquis : comparer quelles réalisations de quelle famille, avec quelles hypothèses ?
q.multiple-generation|Une architecture relationnelle générique peut avoir plusieurs suites constituées.|Formation ramifiée et éventuellement continuation choisie, pas génériques.|Deux successeurs distincts déjà modélisés ; couplage du tournant à une branche reste à construire.|La sélection n'est pas déterminisme ; la progression canonique ne se transfère pas au Step arbitraire.|Question ouverte sur tournant couplé, pas possibilité de ramification.|Conserver ouverte avec test branche par branche, même continuation, recomposition, résidu et admission explicite.
q.quantity|Le domaine exact et ses accords existent avant son nombre.|Positions, occurrences, réalisation exacte, liens, ordre et transports déjà acquis.|Assemblage en quantité intérieure et critère général de comparaison encore à préciser.|Le cardinal seul oublie relations/témoins ; le manque d'empaquetage n'est pas absence de quantité intérieure.|Question ouverte d'interface de comparaison relative à une signature choisie.|Remplacer par : comment assembler et comparer les quantités intérieures déjà constituées sous leurs accords explicites ?
q.converse-traces|Restituer le tout exige les raccords oubliés par la trace.|Exactitude locale, ordre et contiguïté à définir ; racine et extrêmes à fixer.|Reconstruction forte déjà acquise sur RootedGeneratedHistory ; converse générique non établie.|Trace peut oublier raccord de source/cible, couverture des ponts et données initiales/finales.|Question ouverte de converse sur interfaces affaiblies.|Garder la porte ; exiger les ponts effectifs et la couverture avant une promesse de reconstruction.
q.concrete-faithfulness|Des lectures concrètes doivent préserver la distinction souhaitée en plus des occurrences.|Algèbre concrète et lectures concernées ; aucune injectivité générale reçue.|Transport exact d'occurrences déjà acquis ; séparation de cibles après lecture reste à caractériser.|Égalité d'une lecture ne compare pas les constitutions ; l'interface actuelle ne fournit pas cette injectivité.|Question ouverte sur fidélité de certaines lectures.|Nommer la lecture et l'accord suffisant ; ne pas annoncer un nouveau contre-modèle global sans code vérifié.
h.equipped-morphisms|La piste des morphismes équipés donne déjà des comparaisons relationnelles concrètes.|Frontières, fibres complètes, choix et formation source.|Résultats T2 des transports sélectionnés et reconstruction déjà établis.|Comparer des formations arbitraires ou davantage d'opérations demeure distinct.|Piste T6 résiduelle pour extensions ; parties testées rattachées aux T2.|Conserver la piste avec renvoi aux acquis précis ; ne pas appeler tout le programme spéculatif.
h.free-paths|Une propriété universelle pourrait caractériser la construction relationnelle des histoires.|Classe de morphismes et algèbres encore à définir.|Aucune universalité générale établie ; récursions et lois opérationnelles existantes.|Le mot libre et une interprétation de générateurs ne prouvent pas seuls extension unique dans toute catégorie.|Piste T6, pas théorème ni préalable à l'intérieur actuel.|Confirmer son statut ; test : définition des morphismes puis extension unique point par point avec accords.
th.separator-old-completion|La fusion ancienne dans une projection empêche de reconstruire l'intérieur exact.|Noyau à anciens Bool fusionnés, nouvelle partie Unit positive et label étendu fidèle.|Unicité nouvelle mais impossibilité d'ExactInternalCompletion.|Label du porteur étendu ne restaure pas des anciennes occurrences déjà fusionnées par embedOld.|T2 de contre-modèles précis ; reconstruction positive garde embedOldInjective.|Confirmer ; le séparateur ne réfute ni unicité résiduelle ni déploiement intérieur canonique.
x.positive-old-completion|La positivité nouvelle ne répare pas un oubli d'identité ancienne.|Noyau positif avec embedOld non injectif.|Réfutation reconstruction exacte depuis positivité seule.|Les anciennes occurrences fusionnées ne sont plus décodables.|Voie réfutée du noyau faible.|Conserver la leçon et l'acquis positif de reconstruction sous injectivité ancienne.
th.positive-split|La chaîne relationnelle positive est constituée indépendamment du rejet ultérieur.|Épine, témoins et jonction ; lectures de pôles Unit ou Bool.|Parent positif commun et enrichissement obstrué sur la lecture séparée.|La lecture identifiée ne porte pas cette obstruction ; même chaîne ne signifie pas mêmes pôles.|T2 sur couches positives et obstruction explicites.|Confirmer ; le résultat sépare circularité positive et choix d'obstruction, pas périodicité d'une génération.
th.circular-bridge|Le même parent relationnel demeure l'autorité lors du passage aux interfaces historiques.|Présentation positive, lectures de pôles et obstruction ou présentation historique.|Réassemblage et quatre retours exacts de toutes les couches.|Extraction/reconstruction préserve champs et témoins ; pas nouvelle architecture concurrente.|T2 de pont exact ; consommateurs computationnels seulement situés.|Confirmer les retours ; ne pas traiter ce pont comme validation de toute application computationnelle.
th.boundary-extraction|La frontière est lue depuis les relations du début et du terme du même périmètre.|Présentation positive déjà pointée par finalJunction.|ConstitutiveBoundary avec indices, jonction, différence et provenance sélectionnés.|Extraction de données autoritatives ; pas occurrence nouvelle et pas signature universelle.|T2 de frontière sélectionnée du même parent.|Confirmer en la plaçant après constitution intérieure ; ses données reçues ne réfutent pas leur origine relationnelle.
th.boundary-calculus|Les morphismes conservent ce qui équipe la frontière, au-delà des porteurs.|Cinq transports exacts et cinq accords d'indices/témoins distingués.|Identité, inversion, composition, lois pointwise et accord inverse dérivé.|Seules fibres sélectionnées et choix sont comparés ; aucune égalité globale de fonctions.|T2 de signature sélectionnée avec lois explicites.|Confirmer ; conserver distinction cartes réversibles et préservation des choix.
th.equipped-role|Le rôle final porte son témoin exact et lit les données de la frontière fixée.|Frontière déjà pointée ; témoin accordé ; BoundaryTransport riche pour changer de frontière.|Habitant canonique, unicité par choix et transport exact avec conservation des vues.|Source/cible/provenance sont lues sur l'index ; singleton nu ne décrit pas les lois du morphisme riche.|T2 sur une frontière équipée fixe ; grammaire complète acquise ailleurs.|Confirmer ; actualiser la note historique pour renvoyer à la grammaire lot 4 désormais réalisée.
th.separator-closing-witness|Une carte de fibres peut perdre le témoin qui participe à la constitution équipée.|Même frontière, Bool.not sur la fibre fermante et identités ailleurs.|Trois indices préservés, jonction changée, impossibilité de relever ces cartes en BoundaryTransport.|Le choix est une donnée distincte de l'exactitude du porteur de témoins.|T2 de contre-modèle à applications fixées ; identité riche existe.|Confirmer sans généraliser à l'absence de tout transport riche entre ces frontières.
th.separator-provenance-witness|Le témoin de provenance conserve une information distincte de la jonction.|Modèle indépendant Bool, échange de provenance seulement.|Indices/jonction préservés et impossibilité d'enrichir ces mêmes cartes avec provenanceExact.|Une conservation de compatibilité ne reconstitue pas celle de provenance.|T2 de contre-modèle d'accord manquant.|Confirmer la loi séparée, sans exiger la génération de la provenance reçue.
th.separator-positive-recurrence|La répétition d'une valeur nodale ne détermine pas les occurrences constituées.|Chaîne positive à un pas sur un même LocalNode et témoin fermant.|Égalité du nœud terminal/initial ; position positive distincte de cette lecture.|Retour de nœud brut ne signifie pas retour des curseurs historiques ou occurrence périodique.|T2 de données positives ; pas périodicité générée.|Confirmer et rattacher à l'individuation par place/histoire, centrale à la priorité relationnelle.
src.positive-worktree|Archive du découplage positif qui conserve l'autorité des relations.|Sources, empreintes et journaux de l'itération sur base 8a5e494.|Présentation positive, pont et transports initiaux déjà produits.|Date et mention non committée appartiennent à l'archive, pas nécessairement à HEAD livré.|Provenance d'une itération passée ; contrôles rapportés non répétés ici.|Conserver les empreintes ; actualiser seulement le récit courant de livraison hors snapshot gelé.
x.carrier-junction|Une projection des fibres ne conserve pas automatiquement le choix constitutif.|Échange Bool.not de jonction sur indices fixes.|Réfutation de bijection implique conservation du témoin choisi.|La loi junctionExact est absente du porteur nu.|Voie réfutée sur cartes faibles fixées.|Conserver ; montrer les morphismes riches existants comme réponse positive.
x.junction-provenance|La provenance exige son accord propre dans une comparaison.|Jonction conservée et provenance Bool échangée.|Réfutation d'une conservation automatique de provenance.|Deux données de témoins restent distinctes.|Voie réfutée sur une signature sélectionnée.|Conserver provenanceExact séparément ; ne pas en déduire insuffisance de la constitution intérieure.
x.positive-no-recurrence|L'identité des unités n'est pas l'identité de leurs lectures nodales.|Chaîne positive sur même valeur de nœud.|Réfutation positivité interdit toute récurrence brute.|Même nœud peut occuper plusieurs places constituées.|Voie réfutée pour nœuds bruts, pas curseurs stricts.|Conserver et mettre en évidence la différence occurrence/valeur lue.
q.positive-generation|La formation relationnelle construit histoires et domaines, relativement aux pas reçus.|PositiveFormation, nœuds équipés, Step, compatibilité et éventuels témoins de clôture.|Histoires, composition, déploiement, positions et accords exacts déjà réalisés.|Step peut avoir du contenu oublié par deploy ; aucune disponibilité générale ni clôture dérivée.|Question answered dans cette signature ; pas auto-génération des primitives.|Confirmer ; remplacer généralité absolue par construction relative aux pas et témoins concrets reçus.
th.closing-shape-bridge|La forme de frontière sépare l'architecture de son témoin distingué.|Sortes/familles, indices, différence et provenance choisis.|Oubli de la jonction, pointage et réassemblage avec trois retours exacts.|Oublier jonction conserve les autres choix ; pas signature sans données distinguées.|T2 de frontière sélectionnée avant/après pointage.|Confirmer ; ne pas présenter la forme comme génération de toutes ses sortes et indices.
th.closing-pointing-exact|Un témoin positif concret constitue un pointage relationnel utilisable.|Forme B et terme ClosingWitness pour point ; Nonempty seulement pour existence.|Transport exact témoin-pointage et équivalence propositionnelle d'habitation.|Nonempty n'est éliminé que vers Prop ; ne fournit pas une fonction de choix vers Type.|T2 de fibre fermante et enrichissement indexé.|Confirmer existence/choix/donnée séparés ; ne pas confondre l'absence de choix automatique avec absence de relation primitive.
th.closing-empty|Une forme relationnelle n'impose pas l'existence de tout témoin de clôture.|Forme directe avec ClosingWitness vide, indices et provenance disponibles.|Impossibilité de pointage et rôle sur un choix ; impossibilité de provenir d'une frontière déjà équipée.|L'oubli d'un témoin existant conserve une habitation ; modèle vide doit être construit avant pointage.|T2 d'un modèle préalable à clôture.|Confirmer ; ne pas importer frauduleusement ce modèle dans une présentation déjà fermée.
th.closing-role-choice|L'unicité du rôle s'établit relativement à son choix relationnel fixé.|PointedClosingBoundary et jonction concrète.|Habitant du rôle, unicité et accord exact du témoin avec cette jonction.|Habitation du couple choix/rôle est propositionnelle ; aucun choix global unique déduit.|T2 par pointage, pas sur tous les pointages d'une forme.|Confirmer et préciser la quantification sur le choix, sans confondre rôle et jonction.
th.closing-choice-multiplicity|La même architecture peut conserver plusieurs témoins relationnels sans perdre ses rôles par choix.|Modèles de fibres Unit/Bool ; pointages false et true.|Unicité de témoin Unit, deux pointages Bool distincts et rôle unique sur chacun.|L'unicité de chaque fibre de rôle ne fusionne pas les choix à l'échelle de la forme.|T2 de modèles précis ; pas classification universelle des frontières.|Confirmer ; la multiplicité reçue est compatible avec la priorité relationnelle.
x.role-unique-choice|La contraction d'une fibre équipée ne contracte pas toute la famille des choix.|Même forme Bool avec deux choix.|Réfutation unicité du rôle par choix implique jonction unique.|La projection du rôle au choix change le domaine de quantification.|Voie réfutée sur modèle Bool.|Conserver avec leçon centrée sur quantification, pas existence d'un choix arbitraire d'objets.
src.closing-worktree|Archive du traitement relationnel de frontière avant pointage.|Deux modules, modèles et contrôles antérieurs de lot 1.|Forme, pointage, retours et distinctions existence/choix déjà réalisés.|Mentions sans commit et nombres de tâches sont historiques.|Provenance de lot 1 ; aucune revalidation nouvelle.|Conserver archive et hashes ; présenter les acquis depuis l'état livré sans réécrire l'histoire.
th.positive-formation-deployment|Les pas relationnels raccordés construisent l'épine et son domaine de places.|PositiveFormation, State/node/Step et compatibilité des pas concrets.|Déploiement récursif, départ/terme exacts et lien complet conservé à chaque occurrence.|L'épine garde nœuds et compatibilités ; elle peut oublier du contenu supplémentaire de Step.|T2 relatif à la formation ; pas injectivité générale de deploy.|Mettre au centre et confirmer ; recevoir un nœud équipé ne signifie pas recevoir les occurrences déjà individuées.
th.positive-history-composition|La constitution globale est une composition avec raccord typé des relations.|Deux histoires aux états intermédiaires communs.|Deux unités, associativité et déploiement de append par appendAlong.|L'accord terminal réindexe le suffixe ; égalité de valeur numérique ne fournit aucun raccord.|T2 d'opérations dans une formation fixée.|Confirmer ; ne pas annoncer universalité des chemins depuis ces seules lois.
th.positive-occurrence-positions|La genèse des unités intérieures est exactement reliée à celle des places.|PositiveHistory de pas concrets et déploiement relationnel.|Occurrences here/later, vide sans occurrence, distinction des constructeurs et deux retours vers positions.|Occurrence et position appartiennent à cette construction ; nœud/état lu ne les identifie pas.|T2 de la nouvelle formation positive, distinct du générateur strict historique.|Mettre au centre de la carte ; confirmer sans demander que State et tous les témoins soient aussi engendrés.
th.positive-explicit-closing|La clôture intervient après la constitution intérieure et reçoit son témoin propre.|Histoire, occurrence positive dans Type et jonction dans ClosingWitness séparément.|Forme de frontière puis présentation positive avec quatre accords.|Source terminale lue par deploy_final ; positivité n'habite pas la fibre fermante à elle seule.|T2 de fermeture explicite d'une histoire positive.|Confirmer ; cette réception de jonction n'est pas un défaut de constitution des places intérieures.
th.positive-generated-historical-bridge|L'enrichissement d'obstruction garde le même intérieur constitué.|Histoire positive, jonction, pôles et obstruction sur sa présentation déployée.|CircularPresentation et accords exacts des trois couches/déploiement.|La génération positive ne consomme pas le rejet ; le pont le fournit aux interfaces historiques.|T2 de raccord sur le même parent ; pas no-return de tout Step.|Confirmer avec séparation entre histoire générique, parent positif et génération canonique historique.
th.positive-successor-choice|Une sélection de continuation est une donnée relationnelle supplémentaire.|ChosenPositiveContinuation fournit successor et pas depuis chaque état ; modèles dirigé/ramifié.|Walk fini positif ; modèles à deux successeurs ou sans choix global.|Count pilote une itération choisie, pas l'identité des occurrences ni le cardinal primitif du domaine.|T2 sous choix ; non-existence globale permise dans une formation.|Confirmer ; l'architecture générique est relationnelle sans imposer déterminisme ou totalité.
th.separator-generated-unclosed|La génération d'un intérieur positif ne garantit pas sa clôture.|Pas dirigé false→true et famille Compatible correspondante.|Déploiement positif dont ClosingWitness true→false est Empty ; aucun pointage.|La forme lit des extrêmes réellement construits ; absence de témoin final ne supprime pas l'histoire.|T2 de modèle dirigé.|Confirmer ; réfute clôture automatique seulement, pas présentations munies d'une jonction reçue.
th.separator-repeated-positive-occurrences|Les valeurs lues répétées ne constituent pas le principe d'identité des unités.|Deux pas true/false sur Unit, même nœud brut.|Occurrences et positions distinctes ; compatibilités distinctes malgré même nœud.|Le retour d'état est permis dans PositiveHistory ; les positions conservent la participation à la chaîne.|T2 de modèle de formation générique.|Confirmer et donner forte visibilité ; ce séparateur soutient directement l'orientation relationnelle.
x.generation-forces-closure|Le témoin fermant n'est pas déduit de l'existence d'un intérieur.|Modèle dirigé positif à fibre fermante vide.|Réfutation positivité produit une jonction.|L'histoire reste constituée sans pointage final.|Voie réfutée sur formation générique.|Conserver et distinguer manque de clôture de manque de domaine intérieur.
x.positive-unique-successor|Les relations admissibles ne doivent pas être confondues avec une sélection canonique.|Deux pas et deux choix globaux dans le modèle ramifié.|Réfutation successeur unique dans toute formation.|Une continuation choisie lit une branche disponible sans effacer les autres.|Voie réfutée sur interface générique.|Conserver ; tests du tournant futur doivent fixer leur continuation propre.
x.repeated-nodes-merge-positions|Le domaine des unités ne se réduit pas à l'ensemble de leurs valeurs lues.|Même nœud sur deux pas de repeatedHistory.|Réfutation de fusion d'occurrences/positions via égalité nodale.|Lecture nodale est ultérieure et non injective.|Voie réfutée soutenant l'individuation relationnelle.|Conserver et présenter comme un résultat positif pour la priorité relationnelle, pas seule réserve technique.
src.generation-worktree|Archive des premières constructions autonomes d'intérieur depuis des pas admissibles.|Trois modules, modèles, empreintes et contrôles de lot 2.|Histoires et déploiement avec positions/occurrences exactes déjà réalisés.|Sources non committées décrivent l'itération archivée, pas nécessairement l'état courant.|Provenance de lot 2 ; pas nouvelle compilation.|Conserver les traces et orienter le récit courant vers les constructions intérieures acquises.
th.signature-fibre-transport|Comparer des structures exige préserver leurs relations primitivement témoignées.|Trois cartes de sortes et transports exacts de chaque fibre aux indices images.|Vues directes/inverses et retours de toutes les compatibilités et provenances.|Les cartes relationnelles sont reçues, pas déduites des cartes de supports.|T2 relatif à cette signature explicite ; pas toute signature dépendante.|Confirmer ; les sorts typés ne sont pas des unités d'intérieur, et leur exactitude ne suffit pas aux relations.
th.signature-calculus|Les changements de signature conservent les témoins avec leurs indices relationnels.|Transports exacts de signatures et égalités de réindexation.|Identité, inversion, composition, lois pointwise et retours avec reindex explicite.|Aucune égalité globale de structures de fonctions ni opération de pôle conservée.|T2 du calcul de cette signature.|Confirmer les lois ; ne pas appeler absence de signature universelle absence de comparaison relationnelle.
th.signature-boundary-restriction|La frontière équipée conserve des choix dans des familles déjà transportées.|Transports complets ; accords source/cible/différence puis jonction/provenance.|Restriction des familles aux cinq porteurs et construction de BoundaryTransport.|Exactitude de toutes les fibres ne fixe pas automatiquement leurs témoins distingués.|T2 de restriction à mêmes données choisies sous accords explicites.|Confirmer ; distinguer transport de relation et conservation de son témoin choisi.
th.signature-spine-transport|Le transport suit toute la constitution des nœuds et avancées.|Signature transportée fibre par fibre et épine source témoignées.|mapNode/mapSpine, accord du terme, lien complet et composition réindexée.|Pas de paquet d'équivalence générique de toutes les épines ; cette restriction ne retire pas le transport donné.|T2 d'une épine source vers son image.|Confirmer et mettre en avant les témoins internes et successifs conservés dans chaque nœud/lien.
th.signature-position-order|Le transport de la constitution conserve le domaine des places et leurs relations.|Épine fixée, cartes récursives, relations structurales Precedes et Next.|Deux retours de positions ; préservation/réflexion de précédence et succession immédiate.|La bijection de positions seule ne prouve pas ces relations ; preuves séparées sur leurs constructeurs.|T2 sur l'épine source et son image.|Confirmer ; rattacher directement à quantité intérieure et à l'identité des positions malgré nœuds répétés.
th.signature-formation-histories|La reconstruction transporte les relations en conservant tous les pas constituants de l'histoire.|Formation source et transport de sa signature ; State et Step entiers conservés.|Formation cible reconstruite ; deux cartes d'histoires/occurrences avec deux retours.|Données supplémentaires de Step conservées dans histoires ; deploy peut les oublier.|T2 pour F.transport, pas formation cible arbitraire préexistante.|Confirmer avec même State/Step explicités ; le résultat est riche malgré cette borne de généralité.
th.signature-formation-operations|Les relations et la composition de l'intérieur commutent avec la reconstruction.|Histoires composables, reconstruction F.transport et continuation déjà choisie pour walk.|Carrés append/deploy, positions, ordre, succession, liens et itération.|Successor et pas choisi restent reçus ; la reconstruction ne crée aucune disponibilité globale.|T2 d'opérations sur formation reconstruite.|Confirmer et utiliser ces acquis pour une future interface de quantité au lieu de les annoncer manquants.
th.signature-closing-transport|La même clôture reçue se conserve dans une image du domaine construit.|Histoire, occurrence positive, jonction et transport complet de signature.|Transport exact de fibre fermante, parent circulaire cible et frontière avec cinq accords.|Une fibre vide reste sans jonction ; les pôles et leur obstruction ne sont pas transportés.|T2 sur reconstruction ; grammaire des rôles désormais acquise dans lot 4.|Confirmer ; remplacer la note historique hors classification complète par renvoi au lot 4, sans élargir au transport des pôles.
th.separator-sort-fibres|Des supports identiques ne définissent pas une constitution relationnelle identique.|Sortes Bool communes, fibres Compatible Unit et Empty.|Impossibilité de tout transport complet de ces familles.|Oublier les familles laisse des sorts identiques tout en perdant l'habitation de relations.|T2 de modèle précis sur signatures.|Confirmer ; ce modèle soutient l'antériorité des relations pertinentes aux comparaisons, sans prétendre engendrer les supports.
x.sort-transport-fibres|L'accord des supports ne reconstitue pas les familles relationnelles.|Unit/Empty sur mêmes sortes Bool.|Réfutation bijections de sortes suffisent pour transport de fibres.|La signature relationnelle est une donnée propre.|Voie réfutée de transport faible.|Conserver avec transports complets comme résultat positif répondant à cette insuffisance.
src.transport-worktree|Archive des comparaisons qui conservent relations et opérations de l'intérieur.|Sept modules, modèles et contrôles antérieurs de lot 3.|Transports de fibres, épines, positions et formation reconstruite déjà réalisés.|État non committé et compteurs appartiennent à l'archive.|Provenance de lot 3 ; pas validation nouvelle ou globale.|Conserver les empreintes et rattacher les transports à la quantité intérieure constituée.
th.equipped-circular-classification|Les rôles intérieurs lisent les liens des places constituées ; le final lit leur frontière équipée.|Même parent P, position et lien accordés ; rôle final sur choix reçu.|Rôles canoniques, exactitude position-rôle, grammaire à deux branches et deux retours de classification.|Classify oublie le lien/choix au niveau du porteur ; assemble les restitue depuis le même parent.|T2 exhaustif dans CircularRole P ; aucune troisième branche de ce système.|Confirmer ; l'exhaustivité déclarée est un acquis de cette construction, pas une théorie d'objets primitivement classifiés.
th.final-role-no-occurrence|La frontière finale n'ajoute pas une avancée au domaine intérieur constitué.|Grammaire intérieure/finale ; réalisation historique reçue pour les rôles intérieurs.|GeneratedPosition some/none et lecture historique finale none.|Ce none est une lecture par branche ; il ne prouve pas toute non-réalisation pour une famille RealizesFull future.|T2 de lecture du système déclaré et de son pont ; continuation autre histoire permise.|Confirmer en reliant à l'intérieur couvert exactement ; ne pas transformer absence d'attribution en nécessité universelle de toutes les relations.
th.equipped-historical-role-bridge|Les marqueurs nus retrouvent leur contenu à partir de l'autorité du même parent relationnel.|Présentation historique fixée ; réalisation exacte de ses positions dans une histoire.|Transports exacts marqueurs-rôles équipés ; readout concret dans Type ; injectivité de rôles réalisés.|Le parent fournit jonction/liens oubliés par les marqueurs ; injectivité ne couvre pas toutes les occurrences cibles.|T2 du pont sur le même parent et une réalisation reçue.|Confirmer et rendre visible l'accord équipé ; ne pas juger le rôle complet d'après son seul marqueur singleton.
th.equipped-interior-role-transport|Les unités intérieures conservent position et lien entier lors du changement de signature.|Histoire positive, choix de jonction et reconstruction conservant State/Step.|Deux retours de rôles intérieurs, position réindexée et paquet complet transporté.|Nœuds/liens lus peuvent se répéter ; leur égalité ne fusionne pas les positions.|T2 de même histoire et formation reconstruite.|Confirmer et associer à la comparaison de quantité intérieure ; aucune formation arbitraire cible n'est implicitement comparée.
th.equipped-final-role-full-transport|La frontière finale et ses témoins restent équipés sous transport.|CircularBoundaryTransport de la même histoire et jonction choisie.|Rôle final exact avec cinq accords : jonction, source, cible, différence et provenance.|Unicité relative au choix reste ; pas unicité de toutes les jonctions ni rigidité universelle.|T2 des données sélectionnées sous reconstruction.|Confirmer et distinguer préservation des choix de leur génération ou de leur unicité globale.
th.equipped-role-classification-commutes|Le transport conserve la délimitation intérieure/finale du système constitué.|Transports exacts des deux branches sur histoire et reconstruction mêmes State/Step.|Deux retours du rôle complet et commutations classify/Sum.map, generatedPosition/Option.map.|La branche finale reste sans position engendrée ; pôles/obstruction non transportés.|T2 de cette grammaire et reconstruction.|Confirmer ; utiliser ces carrés dans l'assemblage de quantité circulaire intérieure.
th.separator-relative-role-grammar|Le domaine d'une classification dépend du système effectivement construit.|Forme vide, deux choix Bool, extension explicite CircularRole ⊕ Unit.|Impossibilité finale sur fibre vide, témoins de choix distincts, extérieur hors image.|Ajouter une branche change le domaine ; cela ne réfute pas l'exhaustivité du système intérieur/final initial.|T2 de modèles précis ; borne d'annonce relative.|Confirmer et présenter comme test de frontière d'annonce, pas critique de la nécessité relationnelle de l'intérieur.
x.universal-role-exhaustiveness|La constitution d'un système ne promet pas de classer tout système étendu.|Ajout explicite d'un Unit extérieur à CircularRole.|Réfutation d'une exhaustivité sur cette extension.|Le système initial reste exactement classifié ; le texte conceptuel annonçait déjà relativité à la présentation.|Voie réfutée pour inférence universelle, pas pour l'exhaustivité intérieure visée.|Conserver en précisant que changer le type de rôles change la portée ; ne pas imputer cette inférence au projet comme primitive.
src.roles-worktree|Archive de l'équipement des rôles autour du domaine et de sa frontière.|Cinq modules, modèles, audits et contrôles antérieurs de lot 4.|Classification, ponts et transports des rôles déjà produits.|Sources figées de pré-livraison et état Git courant sont des niveaux de provenance distincts.|Provenance de lot 4 ; sans validation computationnelle nouvelle.|Conserver l'archive ; nouvelle analyse conceptuelle séparée du snapshot et de la revue formelle.
'@

$assessmentsById = @{}
foreach ($assessmentLine in ($assessmentRows -split '\r?\n')) {
  if ([string]::IsNullOrWhiteSpace($assessmentLine)) { continue }
  $assessmentParts = $assessmentLine.Split('|')
  if ($assessmentParts.Count -ne 7) { throw "Invalid assessment row: $assessmentLine" }
  if ($assessmentsById.ContainsKey($assessmentParts[0])) { throw "Duplicate id: $($assessmentParts[0])" }
  $assessmentsById[$assessmentParts[0]] = [ordered]@{
    id = $assessmentParts[0]
    role_in_relational_priority = $assessmentParts[1]
    received = $assessmentParts[2]
    constructed = $assessmentParts[3]
    readout = $assessmentParts[4]
    scope = $assessmentParts[5]
    correction = $assessmentParts[6]
  }
}

$assessmentEntries = @()
foreach ($knowledgeNode in $knowledgeData.nodes) {
  if (-not $assessmentsById.ContainsKey($knowledgeNode.id)) { throw "Missing id: $($knowledgeNode.id)" }
  $assessmentEntry = $assessmentsById[$knowledgeNode.id]
  $assessmentEntry.kind = $knowledgeNode.kind
  $assessmentEntry.formal_tier_unchanged = $knowledgeNode.tier
  $assessmentEntry.formal_status_unchanged = $knowledgeNode.status
  $assessmentEntry.original_formal_review = $knowledgeNode.review
  $assessmentEntry.source_anchors = @($knowledgeNode.where)
  $assessmentEntry.lean_refs = @($knowledgeNode.lean_refs)
  $assessmentEntry.evidence_references = @($knowledgeNode.evidence)
  $assessmentEntry.original_links = @($knowledgeNode.links)
  $supportingNodeIds = @($knowledgeData.nodes | Where-Object { @($_.links | Where-Object { $_.to -eq $knowledgeNode.id -and $_.rel -in @('refutes','answers','supports') }).Count -gt 0 } | ForEach-Object { $_.id })
  $assessmentEntry.supporting_node_ids = $supportingNodeIds
  $assessmentEntry.conceptual_review = [ordered]@{ state = 'under-review'; author = 'relations_first_analysis'; date = '2026-10-09'; note = 'Analyse de priorité relationnelle ; aucune promotion de tier ni revalidation globale.' }
  $assessmentEntries += $assessmentEntry
}
if ($assessmentEntries.Count -ne 93 -or $assessmentsById.Count -ne 93) { throw 'Expected exactly 93 assessments.' }
$knowledgeIds = @($knowledgeData.nodes | ForEach-Object { $_.id })
$extraIds = @($assessmentsById.Keys | Where-Object { $_ -notin $knowledgeIds })
if ($extraIds.Count -gt 0) { throw "Unexpected ids: $extraIds" }

$assessmentDocument = [ordered]@{
  schema = 1
  title = 'Relecture exhaustive depuis la priorité relationnelle et le domaine intérieur constitué'
  author = 'relations_first_analysis'
  date = '2026-10-09'
  review_state = 'under-review'
  reference = [ordered]@{
    branch = 'codex/positive-circular-foundations'
    head_transmitted = 'bf13840cd8f39269a77fa25a3b99260a2930230b'
    knowledge_source = 'labyrinth/knowledge.json'
    knowledge_sha256 = (Get-FileHash -LiteralPath $knowledgeFile -Algorithm SHA256).Hash.ToLowerInvariant()
    node_count = $knowledgeData.nodes.Count
    formal_map_base = $knowledgeData.scope.commit
  }
  orientation = "Les relations et leurs témoins constituent les places et les occurrences du domaine intérieur ; les supports typés ne sont pas une extension primitive d'unités individuées. La quantité structurelle précède sa lecture numérique."
  verification_scope = [ordered]@{
    all_source_node_ids_read = $true
    all_assessments_have_nonempty_required_fields = $true
    formal_results_preserved = $true
    new_theorems = 0
    builds_run = 0
    heavy_computation_run = $false
    canonical_files_modified = $false
    computational_layer_globally_validated = $false
    source_reading = 'Sources fondationnelles, déclarations référencées et dépendances nécessaires ; pas nouvel audit exhaustif de chaque ligne du grand module historique. Logs et états formels existants repris uniquement comme provenance.'
  }
  report = 'research/agents/relations-first-analysis/report.md'
  assessments = $assessmentEntries
}
$assessmentFile = Join-Path $taskDirectory 'assessment.json'
$assessmentJson = $assessmentDocument | ConvertTo-Json -Depth 30
[IO.File]::WriteAllText($assessmentFile, $assessmentJson + [Environment]::NewLine, [Text.UTF8Encoding]::new($false))
$verificationData = Get-Content -LiteralPath $assessmentFile -Raw | ConvertFrom-Json
foreach ($verifiedAssessment in $verificationData.assessments) {
  foreach ($requiredField in @('id','received','constructed','readout','scope','correction','role_in_relational_priority')) {
    if ([string]::IsNullOrWhiteSpace($verifiedAssessment.$requiredField)) { throw "Empty field $requiredField for $($verifiedAssessment.id)" }
  }
}
Write-Output "Validated $($verificationData.assessments.Count) assessments, matching all 93 source IDs."
