import RelationalPerimeter.Computation.ConstitutiveSearch.TransportCode
import RelationalPerimeter.Computation.ConstitutiveSearch.AcceptedFrontierNormalization

/-!
# Compositional closure of structural transports

The closure is the free finite closure generated by primitive relation
witnesses.  Existence of a code and executable search for such a code remain
separate notions.

This distinction is essential: failure of direct relation search does not imply
failure in the compositional closure, and failure of a particular code search
still does not prove that no code exists.
-/

namespace ConstitutiveSearch

universe uGenerator

/-- The compositional closure generated by primitive structural witnesses. -/
abbrev TransportClosure
    {State : Type}
    (Generator : State → State → Type uGenerator) :=
  TransportCode Generator

/-- Interpret closure witnesses through the primitive hardened action. -/
def transportClosureAction
    {system : SearchSystem}
    {Generator : system.State → system.State → Type uGenerator}
    (action : AcceptedRelationalAction system Generator) :
    AcceptedRelationalAction
      system
      (TransportClosure Generator) :=
  { toTransport := fun code =>
      code.eval action }

/-- Every primitive generator is included in the closure. -/
def TransportClosure.ofGenerator
    {State : Type}
    {Generator : State → State → Type uGenerator}
    {source target : State}
    (witness : Generator source target) :
    TransportClosure Generator source target :=
  TransportCode.ofGenerator witness

/-- Closure witnesses compose by construction. -/
def TransportClosure.compose
    {State : Type}
    {Generator : State → State → Type uGenerator}
    {source middle target : State}
    (first : TransportClosure Generator source middle)
    (second : TransportClosure Generator middle target) :
    TransportClosure Generator source target :=
  TransportCode.compose first second

/--
Normalize a frontier relative to one explicit executable search over finite
transport codes.
-/
def normalizeWithTransportClosure
    {system : SearchSystem}
    {Generator : system.State → system.State → Type uGenerator}
    (action : AcceptedRelationalAction system Generator)
    (search : RelationSearch (TransportClosure Generator))
    (frontier : List system.State) :
    AcceptedIrreducibleFrontierReduction
      search
      frontier :=
  normalizeAcceptedFrontier
    search
    (transportClosureAction action)
    frontier

end ConstitutiveSearch

/- AXIOM_AUDIT_BEGIN -/
#print axioms ConstitutiveSearch.TransportClosure
#print axioms ConstitutiveSearch.transportClosureAction
#print axioms ConstitutiveSearch.TransportClosure.ofGenerator
#print axioms ConstitutiveSearch.TransportClosure.compose
#print axioms ConstitutiveSearch.normalizeWithTransportClosure
/- AXIOM_AUDIT_END -/
