import RelationalPerimeter.Computation.ConstitutiveSearch.SAT.ParametricSymmetricFamily

/-!
# Parametric multi-level flip-symmetric SAT trajectories

A flip-symmetric trajectory is a proof-relevant SAT path of arbitrary length.
At every level a fresh variable is split, the two generated children satisfy the
local flip-symmetry condition, the false child is transported into the true
child, and the process continues from the retained true child.

This gives an explicit uniform operational width bound for every trajectory in
this family: every recorded width is either 1 or 2, independently of the path
length.
-/

namespace ConstitutiveSearch
namespace SAT

/--
An arbitrary-length generated SAT path whose every local split is certified
flip-symmetric and immediately reducible to its true child.
-/
inductive FlipSymmetricTrajectory
    {rootFormula : Cnf} :
    GeneratedStructuralBranchContext rootFormula →
      GeneratedStructuralBranchContext rootFormula →
        Nat →
          Type where
  | done
      (state : GeneratedStructuralBranchContext rootFormula) :
      FlipSymmetricTrajectory state state 0
  | step
      {parent finish : GeneratedStructuralBranchContext rootFormula}
      {length : Nat}
      (var : Var)
      (fresh :
        StructuralDecisionsAvoid
          var
          parent.context.decisions)
      (symmetric :
        FlipSymmetricAt parent.context.formula var)
      (tail :
        FlipSymmetricTrajectory
          (GeneratedStructuralBranchContext.child
            parent var true fresh)
          finish
          length) :
      FlipSymmetricTrajectory
        parent
        finish
        (length + 1)

namespace FlipSymmetricTrajectory

/--
Compose exact expansion, width-one sibling reduction, and the remaining
trajectory.  Initial and final singleton frontiers therefore have equivalent
viability for every trajectory length.
-/
def preservation
    {rootFormula : Cnf}
    {start finish : GeneratedStructuralBranchContext rootFormula}
    {length : Nat}
    (trajectory :
      FlipSymmetricTrajectory start finish length) :
    AcceptedFrontierPreservation
      (generatedStructuralBranchSystem rootFormula)
      [start]
      [finish] :=
  match trajectory with
  | .done state =>
      AcceptedFrontierPreservation.identity
        (generatedStructuralBranchSystem rootFormula)
        [state]
  | .step var fresh symmetric tail =>
      let expansion :=
        generatedStructuralExpansion
          _
          var
          fresh
      let reduction :=
        reduceFlipSymmetricSiblings
          _
          var
          fresh
          symmetric
      expansion.trans
        (reduction.preservation.trans
          tail.preservation)

/-- End-to-end viability theorem for arbitrary trajectory length. -/
theorem viable_iff
    {rootFormula : Cnf}
    {start finish : GeneratedStructuralBranchContext rootFormula}
    {length : Nat}
    (trajectory :
      FlipSymmetricTrajectory start finish length) :
    FrontierViable
        (generatedStructuralBranchSystem rootFormula)
        [start] ↔
      FrontierViable
        (generatedStructuralBranchSystem rootFormula)
        [finish] :=
  trajectory.preservation.viable_iff

/--
Operational width trace generated by the announced strategy.

Each nonterminal level contributes singleton -> split pair and the recursive
tail begins again at the retained singleton.
-/
def widthTrace
    {rootFormula : Cnf}
    {start finish : GeneratedStructuralBranchContext rootFormula}
    {length : Nat} :
    FlipSymmetricTrajectory start finish length →
      List Nat
  | .done _ =>
      [1]
  | .step _var _fresh _symmetric tail =>
      1 :: 2 :: tail.widthTrace

/-- The operational trace contains one singleton plus two entries per split. -/
theorem widthTrace_length
    {rootFormula : Cnf}
    {start finish : GeneratedStructuralBranchContext rootFormula}
    {length : Nat}
    (trajectory :
      FlipSymmetricTrajectory start finish length) :
    trajectory.widthTrace.length =
      2 * length + 1 := by
  induction trajectory with
  | done state =>
      rfl
  | step var fresh symmetric tail inductionHypothesis =>
      rw [show
        (FlipSymmetricTrajectory.step
          var fresh symmetric tail).widthTrace =
            1 :: 2 :: tail.widthTrace from rfl]
      rw [List.length_cons, List.length_cons]
      rw [inductionHypothesis]
      rw [Nat.mul_succ]

/-- Every width in the arbitrary-length trajectory is exactly 1 or 2. -/
theorem widthTrace_value
    {rootFormula : Cnf}
    {start finish : GeneratedStructuralBranchContext rootFormula}
    {length : Nat}
    (trajectory :
      FlipSymmetricTrajectory start finish length)
    (width : Nat)
    (member : width ∈ trajectory.widthTrace) :
    width = 1 ∨ width = 2 := by
  induction trajectory with
  | done state =>
      cases member with
      | head =>
          exact Or.inl rfl
      | tail _ impossible =>
          cases impossible
  | step var fresh symmetric tail inductionHypothesis =>
      cases member with
      | head =>
          exact Or.inl rfl
      | tail _ afterOne =>
          cases afterOne with
          | head =>
              exact Or.inr rfl
          | tail _ tailMember =>
              exact inductionHypothesis tailMember

/-- Uniform operational bound W(n) <= 2 for every trajectory length n. -/
theorem width_le_two
    {rootFormula : Cnf}
    {start finish : GeneratedStructuralBranchContext rootFormula}
    {length : Nat}
    (trajectory :
      FlipSymmetricTrajectory start finish length)
    (width : Nat)
    (member : width ∈ trajectory.widthTrace) :
    width ≤ 2 := by
  cases trajectory.widthTrace_value width member with
  | inl widthOne =>
      rw [widthOne]
      decide
  | inr widthTwo =>
      rw [widthTwo]
      exact Nat.le_refl 2

/-- A nonempty trajectory actually attains width two at its first split. -/
theorem step_width_two
    {rootFormula : Cnf}
    {parent finish : GeneratedStructuralBranchContext rootFormula}
    {length : Nat}
    (var : Var)
    (fresh :
      StructuralDecisionsAvoid
        var
        parent.context.decisions)
    (symmetric :
      FlipSymmetricAt parent.context.formula var)
    (tail :
      FlipSymmetricTrajectory
        (GeneratedStructuralBranchContext.child
          parent var true fresh)
        finish
        length) :
    2 ∈
      (FlipSymmetricTrajectory.step
        var fresh symmetric tail).widthTrace := by
  exact List.mem_cons_of_mem 1 List.mem_cons_self

end FlipSymmetricTrajectory

end SAT
end ConstitutiveSearch

/- AXIOM_AUDIT_BEGIN -/
#print axioms ConstitutiveSearch.SAT.FlipSymmetricTrajectory
#print axioms ConstitutiveSearch.SAT.FlipSymmetricTrajectory.preservation
#print axioms ConstitutiveSearch.SAT.FlipSymmetricTrajectory.viable_iff
#print axioms ConstitutiveSearch.SAT.FlipSymmetricTrajectory.widthTrace
#print axioms ConstitutiveSearch.SAT.FlipSymmetricTrajectory.widthTrace_length
#print axioms ConstitutiveSearch.SAT.FlipSymmetricTrajectory.widthTrace_value
#print axioms ConstitutiveSearch.SAT.FlipSymmetricTrajectory.width_le_two
#print axioms ConstitutiveSearch.SAT.FlipSymmetricTrajectory.step_width_two
/- AXIOM_AUDIT_END -/
