import RelationalPerimeter.Computation.ConstitutiveSearch.AcceptedRelationalTransport

/-!
# Finite codes for acceptance-preserving transports

A transport used in complexity reasoning must not be treated as a cost-free
arbitrary Lean function.  This module introduces a proof-relevant finite syntax
built from identity, one primitive structural witness, and explicit
composition.

Interpretation into semantic transports is separate from the code itself.
-/

namespace ConstitutiveSearch

universe uGenerator

/-- Free finite compositional syntax generated by one structural relation. -/
inductive TransportCode
    {State : Type}
    (Generator : State → State → Type uGenerator) :
    State → State → Type uGenerator where
  | identity (state : State) :
      TransportCode Generator state state
  | atom
      {source target : State}
      (witness : Generator source target) :
      TransportCode Generator source target
  | compose
      {source middle target : State}
      (first : TransportCode Generator source middle)
      (second : TransportCode Generator middle target) :
      TransportCode Generator source target

namespace TransportCode

/-- Number of primitive generator witnesses occurring in a code. -/
def size
    {State : Type}
    {Generator : State → State → Type uGenerator}
    {source target : State} :
    TransportCode Generator source target → Nat
  | .identity _ => 0
  | .atom _ => 1
  | .compose first second =>
      first.size + second.size

/-- Interpret finite code into a total acceptance-preserving transport. -/
def eval
    {system : SearchSystem}
    {Generator : system.State → system.State → Type uGenerator}
    (action : AcceptedRelationalAction system Generator) :
    {source target : system.State} →
      TransportCode Generator source target →
        AcceptingContinuationTransport system source target
  | _, _, .identity state =>
      AcceptingContinuationTransport.identity
        system
        state
  | _, _, .atom witness =>
      action.toTransport witness
  | _, _, .compose first second =>
      (eval action first).trans
        (eval action second)

/-- Every interpreted code preserves viability in its represented direction. -/
theorem preservesViable
    {system : SearchSystem}
    {Generator : system.State → system.State → Type uGenerator}
    (action : AcceptedRelationalAction system Generator)
    {source target : system.State}
    (code : TransportCode Generator source target) :
    system.Viable source → system.Viable target :=
  (code.eval action).preservesViable

/-- Embed one primitive relation witness into the compositional syntax. -/
def ofGenerator
    {State : Type}
    {Generator : State → State → Type uGenerator}
    {source target : State}
    (witness : Generator source target) :
    TransportCode Generator source target :=
  .atom witness

end TransportCode

end ConstitutiveSearch

/- AXIOM_AUDIT_BEGIN -/
#print axioms ConstitutiveSearch.TransportCode
#print axioms ConstitutiveSearch.TransportCode.size
#print axioms ConstitutiveSearch.TransportCode.eval
#print axioms ConstitutiveSearch.TransportCode.preservesViable
#print axioms ConstitutiveSearch.TransportCode.ofGenerator
/- AXIOM_AUDIT_END -/
